# Generated by Django 5.2.8 on 2025-12-03 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-id"],
                "permissions": (("can_view_on_leave", "Can View On Leave"),),
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
            },
        ),
    ]
