# Generated by Django 5.2 on 2026-05-23 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of salary paid during leave (0–100). Used only when Payment Type is Custom.', max_digits=5, null=True, verbose_name='Payment Percentage'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('custom', 'Custom')], help_text='Specifies how leave days are paid: fully, half, unpaid, or custom percentage', max_length=20, null=True, verbose_name='Payment Type'),
        ),
        migrations.CreateModel(
            name='LeaveTypeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('condition_type', models.CharField(choices=[('gender', 'Gender'), ('once_per_employment', 'Once Per Employment'), ('marital_status', 'Marital Status'), ('nationality', 'Nationality'), ('department', 'Department'), ('employment_type', 'Employment Type'), ('grade', 'Grade'), ('service_duration', 'Service Duration')], max_length=50, verbose_name='Condition Type')),
                ('value', models.CharField(blank=True, help_text='Required for value-based conditions such as gender', max_length=255, null=True, verbose_name='Value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Leave Type Condition',
                'verbose_name_plural': 'Leave Type Conditions',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='leavetype',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='Eligibility conditions evaluated before assigning this leave type to an employee', to='leave.leavetypecondition', verbose_name='Conditions'),
        ),
    ]
