# Generated by Django 5.2 on 2026-06-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendanceallowedip_company_id_and_more'),
        ('leave', '0003_leavetype_payment_percentage_leavetype_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepastleaverestrict',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
