# Generated by Django 5.2 on 2026-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_employeepastleaverestrict_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='custom_reset_days',
            field=models.FloatField(blank=True, help_text='Custom reset interval in days', null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='reset_based',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=30, null=True, verbose_name='Reset Period'),
        ),
        migrations.DeleteModel(
            name='CompanyLeave',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
