# Generated by Django 5.2 on 2026-08-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_holiday_company_id_remove_holiday_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='color',
        ),
    ]
