# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leavetype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, verbose_name='Rejection Reason'),
        ),
    ]
