# Generated by Django 5.2 on 2026-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_historicalticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='prefix',
            field=models.CharField(max_length=3, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
