# Generated by Django 4.2.24 on 2026-07-14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0002_initial"),
        ("hydra_people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("name", models.CharField(max_length=100, verbose_name="Location")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Address")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hydra_locations", to="base.company", verbose_name="Company")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
            ],
            options={"ordering": ("company__company", "name")},
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("name", models.CharField(max_length=100, verbose_name="Section / stage")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="hydra_sections", to="base.department", verbose_name="Department")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sections", to="hydra_coordination.location", verbose_name="Location")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
            ],
            options={"ordering": ("location__company__company", "location__name", "name")},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("name", models.CharField(max_length=100, verbose_name="Team")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teams", to="hydra_coordination.section", verbose_name="Section / stage")),
            ],
            options={"ordering": ("section__location__company__company", "section__location__name", "section__name", "name")},
        ),
        migrations.CreateModel(
            name="ScopeGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate, verbose_name="Valid from")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="Valid until")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="hydra_scope_grants", to="base.company", verbose_name="Company")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="hydra_scope_grants", to="base.department", verbose_name="Department")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scope_grants", to="hydra_coordination.location", verbose_name="Location")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
                ("section", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scope_grants", to="hydra_coordination.section", verbose_name="Section / stage")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scope_grants", to="hydra_coordination.team", verbose_name="Team")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hydra_scope_grants", to=settings.AUTH_USER_MODEL, verbose_name="User")),
            ],
            options={"ordering": ("user__username", "valid_from", "pk")},
        ),
        migrations.CreateModel(
            name="PersonAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate, verbose_name="Valid from")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="Valid until")),
                ("is_primary", models.BooleanField(default=True, verbose_name="Primary assignment")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hydra_person_assignments", to="base.department", verbose_name="Department")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="coordination_assignments", to="hydra_people.person", verbose_name="Person")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="person_assignments", to="hydra_coordination.team", verbose_name="Team")),
            ],
            options={
                "ordering": ("-valid_from", "-pk"),
                "permissions": (("assign_person", "Can assign a Hydra person to an organization team"),),
            },
        ),
        migrations.AddConstraint(model_name="team", constraint=models.UniqueConstraint(fields=("section", "code"), name="hydra_team_section_code_uniq")),
        migrations.AddConstraint(model_name="team", constraint=models.UniqueConstraint(fields=("section", "name"), name="hydra_team_section_name_uniq")),
        migrations.AddConstraint(model_name="section", constraint=models.UniqueConstraint(fields=("location", "code"), name="hydra_section_location_code_uniq")),
        migrations.AddConstraint(model_name="section", constraint=models.UniqueConstraint(fields=("location", "name"), name="hydra_section_location_name_uniq")),
        migrations.AddConstraint(
            model_name="scopegrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("company__isnull", False), ("department__isnull", True), ("location__isnull", True), ("section__isnull", True), ("team__isnull", True)),
                    models.Q(("company__isnull", True), ("department__isnull", False), ("location__isnull", True), ("section__isnull", True), ("team__isnull", True)),
                    models.Q(("company__isnull", True), ("department__isnull", True), ("location__isnull", False), ("section__isnull", True), ("team__isnull", True)),
                    models.Q(("company__isnull", True), ("department__isnull", True), ("location__isnull", True), ("section__isnull", False), ("team__isnull", True)),
                    models.Q(("company__isnull", True), ("department__isnull", True), ("location__isnull", True), ("section__isnull", True), ("team__isnull", False)),
                    _connector="OR",
                ),
                name="hydra_scope_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(model_name="scopegrant", constraint=models.CheckConstraint(check=models.Q(("valid_until__isnull", True), ("valid_until__gte", models.F("valid_from")), _connector="OR"), name="hydra_scope_valid_dates")),
        migrations.AddConstraint(model_name="personassignment", constraint=models.CheckConstraint(check=models.Q(("valid_until__isnull", True), ("valid_until__gte", models.F("valid_from")), _connector="OR"), name="hydra_assignment_valid_dates")),
        migrations.AddConstraint(model_name="location", constraint=models.UniqueConstraint(fields=("company", "code"), name="hydra_location_company_code_uniq")),
        migrations.AddConstraint(model_name="location", constraint=models.UniqueConstraint(fields=("company", "name"), name="hydra_location_company_name_uniq")),
    ]
