# Generated by Django 4.2.24 on 2026-07-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('hydra_coordination', '0003_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('scope_end_scheduled', 'Scope end scheduled'), ('scope_revoked', 'Scope revoked'), ('assignment_end_scheduled', 'Assignment end scheduled'), ('assignment_ended', 'Assignment ended')], max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('notification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notification_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notification_error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_organizationaccessevent', 'Can view organization access events'),),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='personassignment',
            name='termination_mode',
            field=models.CharField(blank=True, choices=[('', 'Not terminated'), ('scheduled', 'Scheduled end'), ('immediate', 'Immediate revocation')], default='', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='personassignment',
            name='termination_reason',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='personassignment',
            name='termination_recorded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='personassignment',
            name='termination_recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_assignment_terminations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scopegrant',
            name='termination_mode',
            field=models.CharField(blank=True, choices=[('', 'Not terminated'), ('scheduled', 'Scheduled end'), ('immediate', 'Immediate revocation')], default='', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='scopegrant',
            name='termination_reason',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='scopegrant',
            name='termination_recorded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scopegrant',
            name='termination_recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_scope_terminations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_scope_grants', to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_scope_grants', to='base.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_grants', to='hydra_coordination.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_grants', to='hydra_coordination.section', verbose_name='Section / stage'),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_grants', to='hydra_coordination.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='scopegrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_scope_grants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='personassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', ''), ('termination_reason', ''), ('termination_recorded_at__isnull', True), ('termination_recorded_by__isnull', True)), models.Q(('termination_mode__in', ('scheduled', 'immediate')), ('termination_recorded_at__isnull', False), ('termination_recorded_by__isnull', False), models.Q(('termination_reason', ''), _negated=True)), _connector='OR'), name='hydra_assignment_termination_audit'),
        ),
        migrations.AddConstraint(
            model_name='personassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', 'scheduled'), _negated=True), ('valid_until__isnull', False), _connector='OR'), name='hydra_assignment_scheduled_end_date'),
        ),
        migrations.AddConstraint(
            model_name='personassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', 'immediate'), _negated=True), ('is_active', False), _connector='OR'), name='hydra_assignment_immediate_inactive'),
        ),
        migrations.AddConstraint(
            model_name='scopegrant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', ''), ('termination_reason', ''), ('termination_recorded_at__isnull', True), ('termination_recorded_by__isnull', True)), models.Q(('termination_mode__in', ('scheduled', 'immediate')), ('termination_recorded_at__isnull', False), ('termination_recorded_by__isnull', False), models.Q(('termination_reason', ''), _negated=True)), _connector='OR'), name='hydra_scope_termination_audit'),
        ),
        migrations.AddConstraint(
            model_name='scopegrant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', 'scheduled'), _negated=True), ('valid_until__isnull', False), _connector='OR'), name='hydra_scope_scheduled_end_date'),
        ),
        migrations.AddConstraint(
            model_name='scopegrant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('termination_mode', 'immediate'), _negated=True), ('is_active', False), _connector='OR'), name='hydra_scope_immediate_inactive'),
        ),
        migrations.AddField(
            model_name='organizationaccessevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_organization_access_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaccessevent',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_organization_access_events', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaccessevent',
            name='person_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='hydra_coordination.personassignment'),
        ),
        migrations.AddField(
            model_name='organizationaccessevent',
            name='scope_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='hydra_coordination.scopegrant'),
        ),
        migrations.AddField(
            model_name='organizationaccessevent',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_organization_access_events_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationaccessevent',
            index=models.Index(fields=['notification_status', 'occurred_at'], name='hydra_access_notify_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('person_assignment__isnull', True), ('scope_grant__isnull', False)), models.Q(('person_assignment__isnull', False), ('scope_grant__isnull', True)), _connector='OR'), name='hydra_access_event_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(('reason', ''), _negated=True), name='hydra_access_event_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ('scope_end_scheduled', 'scope_revoked')), ('person_assignment__isnull', True), ('scope_grant__isnull', False)), models.Q(('action__in', ('assignment_end_scheduled', 'assignment_ended')), ('person_assignment__isnull', False), ('scope_grant__isnull', True)), _connector='OR'), name='hydra_access_event_action_subject'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ('scope_end_scheduled', 'assignment_end_scheduled')), ('effective_until__isnull', False)), models.Q(('action__in', ('scope_revoked', 'assignment_ended')), ('effective_until__isnull', True)), _connector='OR'), name='hydra_access_event_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'not_applicable'), ('subject_user__isnull', True)), models.Q(('subject_user__isnull', False), models.Q(('notification_status', 'not_applicable'), _negated=True)), _connector='OR'), name='hydra_access_event_notify_target'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'sent'), _negated=True), ('notification__isnull', False), _connector='OR'), name='hydra_access_event_sent_record'),
        ),
    ]
