# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recruitment.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='recruitment/profile', validators=[recruitment.models.validate_image])),
                ('portfolio', models.URLField(blank=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('resume', models.FileField(upload_to='recruitment/resume', validators=[recruitment.models.validate_pdf])),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True)),
                ('start_onboard', models.BooleanField(default=False)),
                ('hired', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': (('view_history', 'View Candidate History'), ('archive_candidate', 'Archive Candidate')),
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.company')),
                ('job_position_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='base.jobposition')),
                ('recruitment_managers', models.ManyToManyField(to='employee.employee')),
            ],
            options={
                'permissions': (('archive_recruitment', 'Archive Recruitment'),),
                'unique_together': {('job_position_id', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('stage_type', models.CharField(choices=[('initial', 'Initial'), ('test', 'Test'), ('interview', 'Interview'), ('hired', 'Hired')], default='interview', max_length=20)),
                ('sequence', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recruitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_set', to='recruitment.recruitment')),
                ('stage_managers', models.ManyToManyField(blank=True, to='employee.employee')),
            ],
            options={
                'permissions': (('archive_Stage', 'Archive Stage'),),
                'unique_together': {('recruitment_id', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='StageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.stage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCandidate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile', models.TextField(max_length=100, null=True, validators=[recruitment.models.validate_image])),
                ('portfolio', models.URLField(blank=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('resume', models.TextField(max_length=100, validators=[recruitment.models.validate_pdf])),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True)),
                ('start_onboard', models.BooleanField(default=False)),
                ('hired', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate_history', to='recruitment.candidate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recruitment_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recruitment.recruitment')),
                ('referral', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee')),
                ('stage_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'historical candidate',
                'verbose_name_plural': 'historical candidates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruitment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='recruitment.recruitment'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_referral', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.stage'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('email', 'recruitment_id')},
        ),
    ]
