# Generated by Django 6.0 on 2025-12-09 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruitment",
            options={
                "ordering": ["-id"],
                "permissions": (("archive_recruitment", "Archive Recruitment"),),
                "verbose_name": "Recruitment",
                "verbose_name_plural": "Recruitments",
            },
        ),
        migrations.AlterModelOptions(
            name="skillzonecandidate",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="surveytemplate",
            options={
                "ordering": ["-id"],
                "verbose_name": "Survey Template",
                "verbose_name_plural": "Survey Templates",
            },
        ),
    ]
