# Generated by Django 5.2 on 2026-01-19 09:22

import horilla.models
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_recruitment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to=horilla.models.upload_path, validators=[recruitment.models.validate_pdf], verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Reject Reason'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='format',
            field=models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='max_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max size (In MB)'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='resume',
            field=models.TextField(max_length=100, validators=[recruitment.models.validate_pdf], verbose_name='Resume'),
        ),
    ]
