# Generated by Django 5.2 on 2026-06-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendanceallowedip_company_id_and_more'),
        ('recruitment', '0003_alter_candidate_portfolio_alter_candidate_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentgeneralsetting',
            name='company_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
