# Generated by Django 5.2 on 2026-08-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_historicalstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectreason',
            options={'verbose_name': 'Rejection Reason', 'verbose_name_plural': 'Rejection Reasons'},
        ),
        migrations.AlterModelOptions(
            name='skillzone',
            options={'verbose_name': 'Talent Pool', 'verbose_name_plural': 'Talent Pools'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='start_onboard',
            field=models.BooleanField(default=False, verbose_name='Start Onboarding'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='start_onboard',
            field=models.BooleanField(default=False, verbose_name='Start Onboarding'),
        ),
        migrations.AlterField(
            model_name='skillzone',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Talent Pool'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='skill_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillzonecandidate_set', to='recruitment.skillzone', verbose_name='Talent Pool'),
        ),
    ]
