# Generated by Django 4.2.24 on 2026-07-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hydra_documents", "0001_initial"),
        ("hydra_people", "0002_personapplication_link_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalizationCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("case_type", models.CharField(choices=[("work_permit", "Work permit"), ("temporary_residence", "Temporary residence"), ("visa", "Visa"), ("other", "Other")], max_length=32)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("collecting_documents", "Collecting documents"), ("submitted", "Submitted"), ("additional_information", "Additional information"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired"), ("closed", "Closed")], default="draft", editable=False, max_length=32)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="legalization_cases", to="hydra_people.person")),
                ("responsible", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="responsible_legalization_cases", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("deadline", "person__passport_name", "pk"),
                "permissions": (("assign_legalizationcase", "Can assign legalization cases"), ("transition_legalizationcase", "Can transition legalization cases"), ("link_privatedocument", "Can link private documents to legalization cases")),
            },
        ),
        migrations.CreateModel(
            name="LegalizationCaseDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("role", models.CharField(choices=[("identity", "Identity evidence"), ("application", "Application"), ("decision", "Decision"), ("other", "Other")], default="other", max_length=20)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_links", to="hydra_legalization.legalizationcase")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="legalization_links", to="hydra_documents.privatedocument")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
            ],
            options={"ordering": ("created_at", "pk")},
        ),
        migrations.CreateModel(
            name="LegalizationStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, choices=[("draft", "Draft"), ("collecting_documents", "Collecting documents"), ("submitted", "Submitted"), ("additional_information", "Additional information"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired"), ("closed", "Closed")], max_length=32)),
                ("to_status", models.CharField(choices=[("draft", "Draft"), ("collecting_documents", "Collecting documents"), ("submitted", "Submitted"), ("additional_information", "Additional information"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired"), ("closed", "Closed")], max_length=32)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="legalization_status_changes", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="status_history", to="hydra_legalization.legalizationcase")),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "permissions": (("view_legalizationstatushistory", "Can view legalization status history"),),
                "default_permissions": (),
                "indexes": [models.Index(fields=["case", "occurred_at"], name="hydra_leg_history_idx")],
            },
        ),
        migrations.AddConstraint(model_name="legalizationcasedocument", constraint=models.UniqueConstraint(fields=("case", "document"), name="hydra_leg_case_document_uniq")),
        migrations.AddIndex(model_name="legalizationcase", index=models.Index(fields=["person", "status"], name="hydra_leg_person_status_idx")),
        migrations.AddIndex(model_name="legalizationcase", index=models.Index(fields=["responsible", "status"], name="hydra_leg_owner_status_idx")),
        migrations.AddIndex(model_name="legalizationcase", index=models.Index(fields=["deadline"], name="hydra_leg_deadline_idx")),
    ]
