# Generated by Django 4.2.24 on 2026-07-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_legalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationAutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('deadline_reminder', 'Deadline reminder'), ('deadline_overdue', 'Deadline overdue'), ('validity_reminder', 'Validity reminder'), ('auto_expired', 'Automatically expired')], max_length=24)),
                ('due_date', models.DateField()),
                ('threshold_days', models.PositiveSmallIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('notification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notification_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notification_error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_legalizationautomationevent', 'Can view legalization automation events'),),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='legalizationcase',
            options={'ordering': ('deadline', 'person__passport_name', 'pk'), 'permissions': (('assign_legalizationcase', 'Can assign legalization cases'), ('transition_legalizationcase', 'Can transition legalization cases'), ('link_privatedocument', 'Can link private documents to legalization cases'), ('receive_legalization_escalations', 'Can receive scoped legalization escalations'))},
        ),
        migrations.AddField(
            model_name='legalizationstatushistory',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=12),
        ),
        migrations.AlterField(
            model_name='legalizationstatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalization_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='legalizationstatushistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', False), ('source', 'user')), models.Q(('actor__isnull', True), ('source', 'system')), _connector='OR'), name='hydra_leg_history_source_actor'),
        ),
        migrations.AddField(
            model_name='legalizationautomationevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_events', to='hydra_legalization.legalizationcase'),
        ),
        migrations.AddField(
            model_name='legalizationautomationevent',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_automation_events', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ),
        migrations.AddField(
            model_name='legalizationautomationevent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_automation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='legalizationautomationevent',
            index=models.Index(fields=['notification_status', 'occurred_at'], name='hydra_leg_auto_notify_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalizationautomationevent',
            constraint=models.UniqueConstraint(fields=('case', 'event_type', 'due_date', 'threshold_days', 'recipient'), name='hydra_leg_auto_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationautomationevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type__in', ('deadline_reminder', 'validity_reminder')), ('threshold_days__gt', 0)), models.Q(('event_type__in', ('deadline_overdue', 'auto_expired')), ('threshold_days', 0)), _connector='OR'), name='hydra_leg_auto_threshold'),
        ),
        migrations.AddConstraint(
            model_name='legalizationautomationevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'sent'), _negated=True), ('notification__isnull', False), _connector='OR'), name='hydra_leg_auto_sent_record'),
        ),
    ]
