# Generated by Django 4.2.24 on 2026-07-16 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_documents', '0002_alter_privatedocument_options_and_more'),
        ('hydra_legalization', '0002_legalizationautomationevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationAuthorityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted to authority'), ('reference_assigned', 'Reference assigned'), ('information_requested', 'Additional information requested'), ('information_responded', 'Additional information submitted'), ('approved', 'Decision approved'), ('rejected', 'Decision rejected')], max_length=32)),
                ('occurred_on', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('online_portal', 'Online portal'), ('in_person', 'In person'), ('post', 'Post'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('evidence_sha256', models.CharField(editable=False, max_length=64)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_authority_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_events', to='hydra_legalization.legalizationcase')),
                ('evidence_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_authority_events', to='hydra_documents.privatedocument')),
            ],
            options={
                'ordering': ('-occurred_on', '-recorded_at', '-pk'),
                'permissions': (('record_legalizationauthorityevent', 'Can record legalization authority events'),),
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['case', 'occurred_on', 'recorded_at'], name='hydra_leg_authority_case_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='legalizationauthorityevent',
            constraint=models.UniqueConstraint(fields=('case', 'idempotency_key'), name='hydra_leg_authority_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationauthorityevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type', 'information_requested'), ('response_deadline__isnull', False)), models.Q(models.Q(('event_type', 'information_requested'), _negated=True), ('response_deadline__isnull', True)), _connector='OR'), name='hydra_leg_authority_deadline_shape'),
        ),
        migrations.AddConstraint(
            model_name='legalizationauthorityevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type', 'approved'), ('valid_from__isnull', False), ('valid_until__isnull', False)), models.Q(models.Q(('event_type', 'approved'), _negated=True), ('valid_from__isnull', True), ('valid_until__isnull', True)), _connector='OR'), name='hydra_leg_authority_validity_shape'),
        ),
        migrations.AddConstraint(
            model_name='legalizationauthorityevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type', 'reference_assigned'), _negated=True), models.Q(('reference_number', ''), _negated=True), _connector='OR'), name='hydra_leg_authority_reference'),
        ),
    ]
