# Generated by Django 4.2.24 on 2026-07-16 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_legalization', '0003_legalizationauthorityevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationRenewalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('created', 'Created as renewal'), ('manual', 'Manual historical link')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_renewal_links', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_as_predecessor', to='hydra_legalization.legalizationcase')),
                ('successor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_as_successor', to='hydra_legalization.legalizationcase')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'permissions': (('create_legalizationrenewallink', 'Can create legalization renewal links'),),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='legalizationrenewallink',
            constraint=models.CheckConstraint(check=models.Q(('predecessor', models.F('successor')), _negated=True), name='hydra_leg_renewal_distinct'),
        ),
        migrations.AddConstraint(
            model_name='legalizationrenewallink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reason', ''), ('source', 'created')), models.Q(('source', 'manual'), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='hydra_leg_renewal_reason_shape'),
        ),
    ]
