# Generated by Django 4.2.24 on 2026-07-16 04:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


def backfill_responsibility_baselines(apps, schema_editor):
    LegalizationCase = apps.get_model("hydra_legalization", "LegalizationCase")
    LegalizationWorkEvent = apps.get_model(
        "hydra_legalization", "LegalizationWorkEvent"
    )
    batch = []
    for case_id, responsible_id in (
        LegalizationCase.objects.order_by("pk")
        .values_list("pk", "responsible_id")
        .iterator(chunk_size=1000)
    ):
        batch.append(
            LegalizationWorkEvent(
                case_id=case_id,
                action="responsibility_assigned",
                source="system",
                actor_id=None,
                from_user_id=None,
                to_user_id=responsible_id,
                recipient_id=None,
                reason="Responsibility baseline recorded during migration",
                notification_status="not_applicable",
            )
        )
        if len(batch) == 1000:
            LegalizationWorkEvent.objects.bulk_create(batch, batch_size=1000)
            batch = []
    if batch:
        LegalizationWorkEvent.objects.bulk_create(batch, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('hydra_legalization', '0004_legalizationrenewallink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalizationcase',
            options={'ordering': ('deadline', 'person__passport_name', 'pk'), 'permissions': (('assign_legalizationcase', 'Can assign legalization cases'), ('view_legalizationworkload', 'Can view legalization workload'), ('transition_legalizationcase', 'Can transition legalization cases'), ('link_privatedocument', 'Can link private documents to legalization cases'), ('receive_legalization_escalations', 'Can receive scoped legalization escalations'))},
        ),
        migrations.CreateModel(
            name='LegalizationCaseDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revocation_reason', models.CharField(blank=True, editable=False, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='hydra_legalization.legalizationcase')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_delegations_received', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_delegations_given', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalization_delegations_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-valid_from', '-pk'),
                'permissions': (('manage_legalizationdelegation', 'Can manage legalization case delegations'),),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='LegalizationWorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('responsibility_assigned', 'Responsibility assigned'), ('responsibility_transferred', 'Responsibility transferred'), ('delegation_created', 'Delegation created'), ('delegation_revoked', 'Delegation revoked')], max_length=32)),
                ('source', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=12)),
                ('reason', models.CharField(max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('notification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notification_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notification_error_code', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalization_work_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_events', to='hydra_legalization.legalizationcase')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_events', to='hydra_legalization.legalizationcasedelegation')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalization_work_events_from', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_work_events', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalization_work_events_received', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_work_events_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_legalizationworkevent', 'Can view legalization work events'),),
                'default_permissions': (),
                'indexes': [models.Index(fields=['case', 'occurred_at'], name='hydra_leg_work_case_idx'), models.Index(fields=['notification_status', 'occurred_at'], name='hydra_leg_work_notify_idx')],
            },
        ),
        migrations.RunPython(
            backfill_responsibility_baselines,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(('reason', ''), _negated=True), name='hydra_leg_work_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', False), ('source', 'user')), models.Q(('actor__isnull', True), ('source', 'system')), _connector='OR'), name='hydra_leg_work_source_actor'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action', 'responsibility_assigned'), ('delegation__isnull', True), ('effective_from__isnull', True), ('effective_until__isnull', True), ('from_user__isnull', True)), models.Q(('action', 'responsibility_transferred'), ('delegation__isnull', True), ('effective_from__isnull', True), ('effective_until__isnull', True), ('from_user__isnull', False)), models.Q(('action__in', ('delegation_created', 'delegation_revoked')), ('delegation__isnull', False), ('effective_from__isnull', False), ('effective_until__isnull', False), ('from_user__isnull', False)), _connector='OR'), name='hydra_leg_work_action_shape'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(('from_user__isnull', True), models.Q(('from_user', models.F('to_user')), _negated=True), _connector='OR'), name='hydra_leg_work_distinct_users'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'not_applicable'), ('recipient__isnull', True)), models.Q(('recipient__isnull', False), models.Q(('notification_status', 'not_applicable'), _negated=True)), _connector='OR'), name='hydra_leg_work_notify_target'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'sent'), _negated=True), ('notification__isnull', False), _connector='OR'), name='hydra_leg_work_sent_record'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'responsibility_assigned')), fields=('case', 'action'), name='hydra_leg_initial_owner_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.UniqueConstraint(condition=models.Q(('delegation__isnull', False)), fields=('delegation', 'action'), name='hydra_leg_deleg_event_uniq'),
        ),
        migrations.AddIndex(
            model_name='legalizationcasedelegation',
            index=models.Index(fields=['case', 'is_active', 'valid_from', 'valid_until'], name='hydra_leg_deleg_case_idx'),
        ),
        migrations.AddIndex(
            model_name='legalizationcasedelegation',
            index=models.Index(fields=['deputy', 'is_active', 'valid_from', 'valid_until'], name='hydra_leg_deleg_deputy_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcasedelegation',
            constraint=models.CheckConstraint(check=models.Q(('principal', models.F('deputy')), _negated=True), name='hydra_leg_deleg_distinct_users'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcasedelegation',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__gte', models.F('valid_from'))), name='hydra_leg_deleg_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcasedelegation',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__lte', django.db.models.expressions.CombinedExpression(models.F('valid_from'), '+', models.Value(datetime.timedelta(days=89))))), name='hydra_leg_deleg_bounded_dates'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcasedelegation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_active', True), ('revocation_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False), ('revoked_by__isnull', False), models.Q(('revocation_reason', ''), _negated=True)), _connector='OR'), name='hydra_leg_deleg_revocation_shape'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcasedelegation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('case', 'valid_from', 'valid_until'), name='hydra_leg_deleg_exact_window_uniq'),
        ),
    ]
