# Generated by Django 4.2.24 on 2026-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_legalization', '0005_alter_legalizationcase_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='legalizationworkevent',
            name='hydra_leg_work_notify_target',
        ),
        migrations.AddConstraint(
            model_name='legalizationworkevent',
            constraint=models.CheckConstraint(check=models.Q(('recipient__isnull', False), ('notification_status', 'not_applicable'), _connector='OR'), name='hydra_leg_work_notify_target'),
        ),
    ]
