# Generated by Django 4.2.24 on 2026-07-17 03:18

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone
from django.utils.text import slugify
from hashlib import sha256
import django.db.models.deletion
import uuid


STATUS_ROWS = (
    ('draft', 'Draft'),
    ('collecting_documents', 'Collecting documents'),
    ('submitted', 'Submitted'),
    ('additional_information', 'Additional information'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
    ('expired', 'Expired'),
    ('closed', 'Closed'),
)

PROCEDURE_ROWS = (
    ('work_permit', 'work-permit', 'Work permit'),
    ('temporary_residence', 'temporary-residence', 'Temporary residence'),
    ('visa', 'visa', 'Visa'),
    ('other', 'other', 'Other'),
)

ACTIVE_CASE_STATUSES = {
    'draft',
    'collecting_documents',
    'submitted',
    'additional_information',
}


def _authority_code(name):
    base = slugify(name)[:45] or 'authority'
    digest = sha256(name.encode('utf-8')).hexdigest()[:10]
    return f'{base}-{digest}'


def _case_company_id(apps, case, day):
    PersonAssignment = apps.get_model('hydra_coordination', 'PersonAssignment')
    PersonApplication = apps.get_model('hydra_people', 'PersonApplication')
    assignments = set(
        PersonAssignment.objects.filter(
            person_id=case.person_id,
            is_active=True,
            valid_from__lte=day,
        )
        .filter(Q(valid_until__isnull=True) | Q(valid_until__gte=day))
        .values_list('team__section__location__company_id', flat=True)
    )
    assignments.discard(None)
    if len(assignments) == 1:
        return assignments.pop()
    applications = set(
        PersonApplication.objects.filter(person_id=case.person_id).values_list(
            'candidate__recruitment_id__company_id', flat=True
        )
    )
    applications.discard(None)
    if len(applications) == 1:
        return applications.pop()
    combined = assignments | applications
    return combined.pop() if len(combined) == 1 else None


def seed_and_backfill_legalization_configuration(apps, schema_editor):
    LegalizationAuthority = apps.get_model(
        'hydra_legalization', 'LegalizationAuthority'
    )
    LegalizationAuthorityEvent = apps.get_model(
        'hydra_legalization', 'LegalizationAuthorityEvent'
    )
    LegalizationCase = apps.get_model('hydra_legalization', 'LegalizationCase')
    LegalizationProcedureType = apps.get_model(
        'hydra_legalization', 'LegalizationProcedureType'
    )
    LegalizationProcedureStatus = apps.get_model(
        'hydra_legalization', 'LegalizationProcedureStatus'
    )

    authority_by_name = {}
    authority_channels = {}
    for name, channel in LegalizationAuthorityEvent.objects.order_by().values_list(
        'authority', 'channel'
    ):
        normalized = ' '.join((name or '').split())
        if not normalized:
            continue
        authority_channels.setdefault(normalized, set()).add(channel)
    for name, channels in authority_channels.items():
        authority, _created = LegalizationAuthority.objects.get_or_create(
            company_id=None,
            code=_authority_code(name),
            defaults={
                'name': name,
                'jurisdiction': '',
                'allowed_channels': sorted(channels),
                'is_active': True,
            },
        )
        authority_by_name[name] = authority

    procedures = {}
    for case_type, code, name in PROCEDURE_ROWS:
        procedure, _created = LegalizationProcedureType.objects.get_or_create(
            company_id=None,
            code=code,
            defaults={
                'name': name,
                'case_type': case_type,
                'description': '',
                'default_deadline_days': None,
                'renewal_lead_days': 90,
                'requires_authority': True,
                'is_active': True,
            },
        )
        procedures[case_type] = procedure
        for index, (status, label) in enumerate(STATUS_ROWS):
            LegalizationProcedureStatus.objects.get_or_create(
                procedure_id=procedure.pk,
                status=status,
                defaults={
                    'label': label,
                    'sort_order': index,
                    'is_active': True,
                },
            )

    for case_type, authority_name in LegalizationAuthorityEvent.objects.order_by().values_list(
        'case__case_type', 'authority'
    ).distinct():
        normalized = ' '.join((authority_name or '').split())
        authority = authority_by_name.get(normalized)
        procedure = procedures.get(case_type)
        if authority and procedure:
            procedure.authorities.add(authority)

    unresolved = []
    day = timezone.localdate()
    for case in LegalizationCase.objects.order_by('pk').iterator(chunk_size=500):
        company_id = _case_company_id(apps, case, day)
        procedure = procedures.get(case.case_type)
        if company_id is None or procedure is None:
            unresolved.append(str(case.uuid))
            continue
        authorities = [
            {
                'uuid': str(authority.uuid),
                'company_id': authority.company_id,
                'code': authority.code,
                'name': authority.name,
                'jurisdiction': authority.jurisdiction,
                'allowed_channels': list(authority.allowed_channels),
            }
            for authority in procedure.authorities.filter(is_active=True).order_by('pk')
        ]
        legacy_authority_policy_pending = (
            not authorities and case.status in ACTIVE_CASE_STATUSES
        )
        snapshot = {
            'procedure_uuid': str(procedure.uuid),
            'procedure_company_id': None,
            'case_company_id': company_id,
            'code': procedure.code,
            'name': procedure.name,
            'case_type': procedure.case_type,
            'default_deadline_days': procedure.default_deadline_days,
            'renewal_lead_days': procedure.renewal_lead_days,
            'requires_authority': bool(authorities) or legacy_authority_policy_pending,
            'legacy_authority_policy_pending': legacy_authority_policy_pending,
            'statuses': [
                {'status': status, 'label': label, 'sort_order': index}
                for index, (status, label) in enumerate(STATUS_ROWS)
            ],
            'requirements': [],
            'authorities': authorities,
        }
        LegalizationCase.objects.filter(pk=case.pk).update(
            company_id=company_id,
            procedure_type_id=procedure.pk,
            procedure_snapshot=snapshot,
        )
    if unresolved:
        sample = ', '.join(unresolved[:20])
        raise RuntimeError(
            'Cannot infer one legalization company for existing case(s): '
            f'{sample}. Resolve Person organization/application links and retry.'
        )

    for event in LegalizationAuthorityEvent.objects.order_by('pk').iterator(
        chunk_size=500
    ):
        normalized = ' '.join((event.authority or '').split())
        authority = authority_by_name.get(normalized)
        if authority is None:
            raise RuntimeError(
                f'Cannot backfill authority dictionary for event {event.pk}.'
            )
        snapshot = {
            'uuid': str(authority.uuid),
            'company_id': authority.company_id,
            'code': authority.code,
            'name': authority.name,
            'jurisdiction': authority.jurisdiction,
            'allowed_channels': list(authority.allowed_channels),
        }
        LegalizationAuthorityEvent.objects.filter(pk=event.pk).update(
            authority_config_id=authority.pk,
            authority_snapshot=snapshot,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_documents', '0003_document_types_and_versions'),
        ('base', '0002_initial'),
        ('hydra_coordination', '0004_organizationaccessevent_and_more'),
        ('hydra_people', '0005_person_duplicate_merge'),
        ('hydra_legalization', '0006_remove_legalizationworkevent_hydra_leg_work_notify_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('allowed_channels', models.JSONField(default=list)),
            ],
            options={
                'ordering': ('company__company', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LegalizationConfigurationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(choices=[('procedure', 'Procedure'), ('authority', 'Authority'), ('requirement', 'Requirement')], max_length=20)),
                ('entity_uuid', models.UUIDField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=12)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_legalizationconfigurationevent', 'Can view legalization configuration history'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LegalizationProcedureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=160)),
                ('required_before_status', models.CharField(choices=[('draft', 'Draft'), ('collecting_documents', 'Collecting documents'), ('submitted', 'Submitted'), ('additional_information', 'Additional information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed')], max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('procedure', 'sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LegalizationProcedureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting_documents', 'Collecting documents'), ('submitted', 'Submitted'), ('additional_information', 'Additional information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed')], max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('procedure', 'sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LegalizationProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=160)),
                ('case_type', models.CharField(choices=[('work_permit', 'Work permit'), ('temporary_residence', 'Temporary residence'), ('visa', 'Visa'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('default_deadline_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('renewal_lead_days', models.PositiveSmallIntegerField(default=90)),
                ('requires_authority', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('company__company', 'name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='legalizationauthorityevent',
            name='authority_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='legalizationcase',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_cases', to='base.company'),
        ),
        migrations.AddField(
            model_name='legalizationcase',
            name='procedure_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddIndex(
            model_name='legalizationcase',
            index=models.Index(fields=['company', 'status'], name='hydra_leg_company_status_idx'),
        ),
        migrations.AddField(
            model_name='legalizationproceduretype',
            name='authorities',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='hydra_legalization.legalizationauthority'),
        ),
        migrations.AddField(
            model_name='legalizationproceduretype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_procedures', to='base.company'),
        ),
        migrations.AddField(
            model_name='legalizationproceduretype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='legalizationproceduretype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurestatus',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurestatus',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurestatus',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_rules', to='hydra_legalization.legalizationproceduretype'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurerequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurerequirement',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_requirements', to='hydra_documents.privatedocumenttype'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurerequirement',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='legalizationprocedurerequirement',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='hydra_legalization.legalizationproceduretype'),
        ),
        migrations.AddField(
            model_name='legalizationconfigurationevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalization_configuration_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalizationauthority',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_legalization_authorities', to='base.company'),
        ),
        migrations.AddField(
            model_name='legalizationauthority',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='legalizationauthority',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='legalizationauthorityevent',
            name='authority_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hydra_legalization.legalizationauthority'),
        ),
        migrations.AddField(
            model_name='legalizationcase',
            name='procedure_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='hydra_legalization.legalizationproceduretype'),
        ),
        migrations.AddConstraint(
            model_name='legalizationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'collecting_documents', 'submitted', 'additional_information'))), fields=('person', 'company', 'procedure_type'), name='hydra_leg_active_procedure_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationproceduretype',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='hydra_leg_procedure_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationproceduretype',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='hydra_leg_procedure_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationproceduretype',
            constraint=models.CheckConstraint(check=models.Q(('default_deadline_days__isnull', True), ('default_deadline_days__gt', 0), _connector='OR'), name='hydra_leg_procedure_deadline_positive'),
        ),
        migrations.AddConstraint(
            model_name='legalizationproceduretype',
            constraint=models.CheckConstraint(check=models.Q(('renewal_lead_days__gt', 0)), name='hydra_leg_procedure_renewal_positive'),
        ),
        migrations.AddConstraint(
            model_name='legalizationprocedurestatus',
            constraint=models.UniqueConstraint(fields=('procedure', 'status'), name='hydra_leg_procedure_status_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationprocedurerequirement',
            constraint=models.UniqueConstraint(fields=('procedure', 'code'), name='hydra_leg_requirement_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationprocedurerequirement',
            constraint=models.UniqueConstraint(fields=('procedure', 'document_type', 'required_before_status'), name='hydra_leg_requirement_type_status_uniq'),
        ),
        migrations.AddIndex(
            model_name='legalizationconfigurationevent',
            index=models.Index(fields=['entity_type', 'entity_uuid', 'occurred_at'], name='hydra_leg_config_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalizationauthority',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='hydra_leg_authority_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalizationauthority',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='hydra_leg_authority_global_code_uniq'),
        ),
        migrations.RunPython(
            seed_and_backfill_legalization_configuration,
            noop_reverse,
        ),
    ]
