# Generated by Django 4.2.24 on 2026-07-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_legalization', '0007_legalization_configuration_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalizationcase',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hydra_legalization_cases',
                to='base.company',
            ),
        ),
        migrations.AlterField(
            model_name='legalizationcase',
            name='procedure_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cases',
                to='hydra_legalization.legalizationproceduretype',
            ),
        ),
        migrations.AlterField(
            model_name='legalizationauthorityevent',
            name='authority_config',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='events',
                to='hydra_legalization.legalizationauthority',
            ),
        ),
    ]
