# Generated by Django 4.2.24 on 2026-07-17 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydra_people', '0005_person_duplicate_merge'),
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', editable=False, max_length=16)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolution_reason', models.CharField(blank=True, editable=False, max_length=500)),
                ('target_kind', models.CharField(choices=[('person', 'Person'), ('legalization_case', 'Legalization case'), ('arrival_plan', 'Arrival plan'), ('housing_assignment', 'Housing assignment'), ('onboarding_handoff', 'Onboarding handoff')], default='person', editable=False, max_length=32)),
                ('target_uuid', models.UUIDField(editable=False)),
                ('target_label', models.CharField(editable=False, max_length=255)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hydra_tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_tasks', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_tasks', to='hydra_people.person')),
            ],
            options={
                'ordering': ('status', 'due_at', '-created_at', 'pk'),
                'permissions': (('assign_hydratask', 'Can assign Hydra tasks'), ('transition_hydratask', 'Can transition Hydra tasks'), ('reopen_hydratask', 'Can reopen completed or cancelled Hydra tasks'), ('view_all_hydratask', 'Can view all Hydra tasks in current scope')),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='HydraTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('reassigned', 'Reassigned'), ('status_changed', 'Status changed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('from_due_at', models.DateTimeField(blank=True, null=True)),
                ('to_due_at', models.DateTimeField(blank=True, null=True)),
                ('from_priority', models.CharField(blank=True, max_length=12)),
                ('to_priority', models.CharField(blank=True, max_length=12)),
                ('changed_fields', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_task_events', to=settings.AUTH_USER_MODEL)),
                ('from_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_task_events_assigned_from', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hydra_tasks.hydratask')),
                ('to_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_task_events_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='HydraTaskNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='hydra_tasks.hydrataskevent')),
                ('notification', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_task_notification_deliveries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='hydra_tasks.hydratask')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='hydratasknotificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient'), name='hyd_task_delivery_event_recipient_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hydrataskevent',
            constraint=models.UniqueConstraint(fields=('task', 'sequence'), name='hyd_task_event_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hydrataskevent',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_task_event_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='hydratask',
            index=models.Index(fields=['company', 'status', 'due_at'], name='hyd_task_company_state_idx'),
        ),
        migrations.AddIndex(
            model_name='hydratask',
            index=models.Index(fields=['assignee', 'status', 'due_at'], name='hyd_task_assignee_state_idx'),
        ),
        migrations.AddIndex(
            model_name='hydratask',
            index=models.Index(fields=['person', 'status'], name='hyd_task_person_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='hydratask',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='hyd_task_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='hydratask',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False), ('is_active', True)), name='hyd_task_active_creator_shape'),
        ),
        migrations.AddConstraint(
            model_name='hydratask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', False), ('status', 'completed')), models.Q(('cancelled_at__isnull', False), ('completed_at__isnull', True), ('status', 'cancelled')), models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', True), ('status__in', ('open', 'in_progress'))), _connector='OR'), name='hyd_task_terminal_timestamp_shape'),
        ),
        migrations.AddConstraint(
            model_name='hydratask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolution_reason__gt', ''), ('status__in', ('completed', 'cancelled'))), models.Q(('resolution_reason', ''), ('status__in', ('open', 'in_progress'))), _connector='OR'), name='hyd_task_resolution_reason_shape'),
        ),
    ]
