# Generated by Django 4.2.24 for Horilla's dynamic User field.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new_employee",
            field=models.BooleanField(default=False),
        ),
    ]
