# Generated by Django 4.2.24 on 2026-07-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_coordination', '0003_alter_location_options'),
        ('hydra_people', '0003_employee_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Facility')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housing_facilities', to='hydra_coordination.location', verbose_name='Location')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('location__company__company', 'location__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HousingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Room')),
                ('floor', models.CharField(blank=True, max_length=40, verbose_name='Floor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hydra_housing.housingfacility', verbose_name='Facility')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('facility__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HousingBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=60, verbose_name='Bed')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hydra_housing.housingroom', verbose_name='Room')),
            ],
            options={
                'ordering': ('room__facility__name', 'room__name', 'label'),
            },
        ),
        migrations.CreateModel(
            name='HousingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notes')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hydra_housing.housingbed', verbose_name='Bed')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housing_assignments', to='hydra_people.person', verbose_name='Person')),
            ],
            options={
                'ordering': ('-valid_from', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='housingroom',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='hyd_house_room_facility_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='housingfacility',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='hyd_house_facility_location_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='housingbed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='hyd_house_bed_room_label_uniq'),
        ),
        migrations.AddIndex(
            model_name='housingassignment',
            index=models.Index(fields=['bed', 'valid_from', 'valid_until'], name='hyd_house_bed_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='housingassignment',
            index=models.Index(fields=['person', 'valid_from', 'valid_until'], name='hyd_house_person_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='housingassignment',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='hyd_house_assignment_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='housingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('valid_until__isnull', True)), fields=('bed',), name='hyd_house_open_bed_uniq'),
        ),
        migrations.AddConstraint(
            model_name='housingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('valid_until__isnull', True)), fields=('person',), name='hyd_house_open_person_uniq'),
        ),
    ]
