# Generated by Django 4.2.24 on 2026-07-16

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion
import uuid


def backfill_housing_assignment_events(apps, schema_editor):
    HousingAssignment = apps.get_model("hydra_housing", "HousingAssignment")
    HousingAssignmentEvent = apps.get_model(
        "hydra_housing", "HousingAssignmentEvent"
    )
    today = timezone.localdate()
    for assignment in HousingAssignment.objects.order_by("pk").iterator(chunk_size=1000):
        created_on = (
            assignment.created_at.date()
            if assignment.created_at is not None
            else assignment.valid_from
        )
        origin_action = (
            "reserved" if assignment.valid_from > created_on else "assigned"
        )
        HousingAssignmentEvent.objects.create(
            assignment_id=assignment.pk,
            action=origin_action,
            actor_id=None,
            source="system",
            effective_on=assignment.valid_from,
            scheduled_until=assignment.valid_until,
            reason="Housing assignment baseline recorded during migration.",
        )
        if not assignment.is_active:
            HousingAssignmentEvent.objects.create(
                assignment_id=assignment.pk,
                action="cancelled",
                actor_id=None,
                source="system",
                effective_on=assignment.valid_from,
                scheduled_until=assignment.valid_until,
                reason="Inactive housing period baseline recorded during migration.",
            )
        elif assignment.valid_until is not None and assignment.valid_until <= today:
            HousingAssignmentEvent.objects.create(
                assignment_id=assignment.pk,
                action="ended",
                actor_id=None,
                source="system",
                effective_on=assignment.valid_until,
                scheduled_until=assignment.valid_until,
                reason="Housing assignment end baseline recorded during migration.",
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hydra_housing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="housingassignment",
            options={
                "ordering": ("-valid_from", "-pk"),
                "permissions": (
                    ("reserve_housingassignment", "Can reserve housing"),
                    (
                        "cancel_housingreservation",
                        "Can cancel housing reservations",
                    ),
                    ("move_housingassignment", "Can move housing assignments"),
                ),
            },
        ),
        migrations.CreateModel(
            name="HousingAssignmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Housing assigned"),
                            ("reserved", "Housing reserved"),
                            ("ended", "Stay ended"),
                            ("cancelled", "Reservation cancelled"),
                            ("moved_out", "Moved out"),
                            ("moved_in", "Moved in"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        default="user",
                        max_length=12,
                    ),
                ),
                ("effective_on", models.DateField()),
                ("scheduled_until", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="housing_assignment_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="hydra_housing.housingassignment",
                    ),
                ),
                (
                    "related_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_events",
                        to="hydra_housing.housingassignment",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "permissions": (
                    (
                        "view_housingassignmentevent",
                        "Can view housing assignment events",
                    ),
                ),
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["assignment", "occurred_at"],
                        name="hyd_house_evt_assign_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.CheckConstraint(
                check=models.Q(("reason", ""), _negated=True),
                name="hyd_house_evt_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("actor__isnull", False), ("source", "user")),
                    models.Q(("actor__isnull", True), ("source", "system")),
                    _connector="OR",
                ),
                name="hyd_house_evt_source_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("action__in", ("moved_out", "moved_in")),
                        ("related_assignment__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            ("action__in", ("moved_out", "moved_in")),
                            _negated=True,
                        ),
                        ("related_assignment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="hyd_house_evt_action_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("related_assignment__isnull", True),
                    models.Q(
                        ("assignment", models.F("related_assignment")),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="hyd_house_evt_distinct_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("action__in", ("assigned", "reserved", "moved_in"))
                ),
                fields=("assignment",),
                name="hyd_house_evt_origin_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="housingassignmentevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("action__in", ("ended", "cancelled", "moved_out"))
                ),
                fields=("assignment",),
                name="hyd_house_evt_terminal_uniq",
            ),
        ),
        migrations.RunPython(
            backfill_housing_assignment_events,
            migrations.RunPython.noop,
        ),
    ]
