# Generated by Django 4.2.24 on 2026-07-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_legacy_floor_hierarchy(apps, schema_editor):
    HousingBuilding = apps.get_model("hydra_housing", "HousingBuilding")
    HousingFloor = apps.get_model("hydra_housing", "HousingFloor")
    HousingRoom = apps.get_model("hydra_housing", "HousingRoom")
    rooms = HousingRoom.objects.exclude(floor="").order_by("facility_id", "pk")
    buildings = {}
    floors = {}
    for room in rooms.iterator(chunk_size=1000):
        building = buildings.get(room.facility_id)
        if building is None:
            building, _created = HousingBuilding.objects.get_or_create(
                facility_id=room.facility_id,
                name="Legacy building",
                defaults={
                    "notes": (
                        "Migration placeholder for rooms that previously stored only "
                        "a free-text floor label. Rename after facility verification."
                    )
                },
            )
            buildings[room.facility_id] = building
        key = (building.pk, room.floor)
        floor = floors.get(key)
        if floor is None:
            floor, _created = HousingFloor.objects.get_or_create(
                building_id=building.pk,
                name=room.floor,
            )
            floors[key] = floor
        HousingRoom.objects.filter(pk=room.pk).update(floor_unit_id=floor.pk)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_housing', '0002_alter_housingassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Building')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='hydra_housing.housingfacility', verbose_name='Facility')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('facility__name', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='housingassignment',
            options={'ordering': ('-valid_from', '-pk'), 'permissions': (('reserve_housingassignment', 'Can reserve housing'), ('renew_housingreservation', 'Can renew housing reservations'), ('confirm_housingreservation', 'Can confirm housing reservations'), ('cancel_housingreservation', 'Can cancel housing reservations'), ('move_housingassignment', 'Can move housing assignments'))},
        ),
        migrations.AddField(
            model_name='housingassignment',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Temporary reservation expires at'),
        ),
        migrations.AlterField(
            model_name='housingassignmentevent',
            name='action',
            field=models.CharField(choices=[('assigned', 'Housing assigned'), ('reserved', 'Housing reserved'), ('ended', 'Stay ended'), ('cancelled', 'Reservation cancelled'), ('renewed', 'Reservation renewed'), ('confirmed', 'Reservation confirmed'), ('expired', 'Reservation expired'), ('moved_out', 'Moved out'), ('moved_in', 'Moved in')], max_length=16),
        ),
        migrations.CreateModel(
            name='HousingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=60, verbose_name='Floor')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='Sort order')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='hydra_housing.housingbuilding', verbose_name='Building')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('building__facility__name', 'building__name', 'sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='housingroom',
            name='floor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hydra_housing.housingfloor', verbose_name='Building / floor'),
        ),
        migrations.AddConstraint(
            model_name='housingfloor',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='hyd_house_floor_building_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='housingbuilding',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='hyd_house_building_facility_name_uniq'),
        ),
        migrations.RunPython(
            backfill_legacy_floor_hierarchy,
            migrations.RunPython.noop,
        ),
    ]
