# Generated by Django 4.2.24 on 2026-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_housing', '0003_housing_hierarchy_reservations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='housingassignmentevent',
            name='hyd_house_evt_terminal_uniq',
        ),
        migrations.AddConstraint(
            model_name='housingassignmentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('action__in', ('ended', 'cancelled', 'expired', 'moved_out'))), fields=('assignment',), name='hyd_house_evt_terminal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='housingassignmentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'confirmed')), fields=('assignment',), name='hyd_house_evt_confirmed_uniq'),
        ),
    ]
