# Generated by Django 5.2.8 on 2025-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_automations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailautomation",
            name="delivery_channel",
            field=models.CharField(
                choices=[
                    ("email", "Send as Email"),
                    ("notification", "Send as Notification"),
                    ("both", "Send as Email and Notification"),
                ],
                default="email",
                max_length=50,
                verbose_name="Choose Delivery Channel",
            ),
        ),
    ]
