# Generated by Django 5.2 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dynamicemailconfiguration_company_id_and_more'),
        ('horilla_automations', '0002_alter_mailautomation_delivery_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailautomation',
            name='mail_details',
            field=models.CharField(help_text='Fill mail template details(reciever/instance, `self` will be the person who trigger the automation)', max_length=250, verbose_name='Mail Details'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.horillamailtemplate', verbose_name='Mail Template'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='model',
            field=models.CharField(choices=[], max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='template_attachments',
            field=models.ManyToManyField(blank=True, related_name='template_attachment', to='base.horillamailtemplate', verbose_name='Template Attachments'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='trigger',
            field=models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_delete', 'On Delete')], max_length=10, verbose_name='Trigger Condition'),
        ),
    ]
