# Generated by Django 4.2.24 on 2026-07-17 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_people', '0005_person_duplicate_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraNotificationEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(editable=False, max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('legacy', 'Horilla notification'), ('organization_scope_end', 'Scope end scheduled'), ('organization_scope_revoked', 'Scope revoked'), ('organization_assignment_end', 'Assignment end scheduled'), ('organization_assignment_ended', 'Assignment ended'), ('arrival_upcoming', 'Arrival approaching'), ('arrival_overdue', 'Arrival overdue'), ('legalization_deadline', 'Legalization deadline'), ('legalization_overdue', 'Legalization overdue'), ('legalization_validity', 'Validity ending'), ('legalization_expired', 'Legalization expired'), ('legalization_assigned', 'Responsibility assigned'), ('legalization_transferred', 'Responsibility transferred'), ('legalization_deputy', 'Deputy appointed'), ('legalization_deputy_revoked', 'Deputy appointment revoked'), ('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('task_reassigned', 'Task reassigned'), ('task_status_changed', 'Task status changed'), ('task_completed', 'Task completed'), ('task_cancelled', 'Task cancelled'), ('task_reopened', 'Task reopened'), ('onboarding_ready', 'Onboarding ready'), ('onboarding_task_changed', 'Onboarding task changed')], max_length=48)),
                ('category', models.CharField(choices=[('legacy', 'Horilla'), ('organization', 'Organization'), ('arrivals', 'Arrivals'), ('legalization', 'Legalization'), ('tasks', 'Tasks'), ('onboarding', 'Onboarding')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Urgent')], max_length=12)),
                ('target_kind', models.CharField(choices=[('general', 'General'), ('organization', 'Organization'), ('person', 'Person'), ('legalization_case', 'Legalization case'), ('arrival_plan', 'Arrival plan'), ('onboarding_handoff', 'Onboarding handoff'), ('hydra_task', 'Hydra task')], default='general', max_length=24)),
                ('target_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('redirect_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_envelopes', to='base.company')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_envelope', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_envelopes', to='hydra_people.person')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_envelopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='HydraNotificationStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('imported', 'Imported from Horilla'), ('read', 'Marked as read'), ('unread', 'Marked as unread'), ('opened', 'Opened'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=16)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_state_events', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_events', to='hydra_notifications.hydranotificationenvelope')),
            ],
            options={
                'ordering': ('sequence', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='HydraNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_min_severity', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Urgent')], default='warning', max_length=12)),
                ('browser_sound_enabled', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_hydra_notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HydraNotificationEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('failed', 'Waiting for retry'), ('sent', 'Sent'), ('dead', 'Retries exhausted'), ('not_applicable', 'Not applicable')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='hydra_notifications.hydranotificationenvelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_notification_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='hydranotificationstateevent',
            constraint=models.UniqueConstraint(fields=('envelope', 'sequence'), name='hyd_not_event_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationstateevent',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_not_event_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationpreference',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='hyd_not_pref_version_positive'),
        ),
        migrations.AddIndex(
            model_name='hydranotificationenvelope',
            index=models.Index(fields=['recipient', 'archived_at', 'read_at', 'occurred_at'], name='hyd_not_rec_state_time_idx'),
        ),
        migrations.AddIndex(
            model_name='hydranotificationenvelope',
            index=models.Index(fields=['target_kind', 'target_uuid'], name='hyd_not_target_idx'),
        ),
        migrations.AddIndex(
            model_name='hydranotificationenvelope',
            index=models.Index(fields=['recipient', 'category', 'severity'], name='hyd_not_rec_cat_sev_idx'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationenvelope',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='hyd_not_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationenvelope',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key', ''), _negated=True), name='hyd_not_idempotency_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationenvelope',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_kind__in', ('general', 'organization')), ('target_uuid__isnull', True)), models.Q(('target_kind__in', ('person', 'legalization_case', 'arrival_plan', 'onboarding_handoff', 'hydra_task')), ('target_uuid__isnull', False)), _connector='OR'), name='hyd_not_target_shape'),
        ),
        migrations.AddIndex(
            model_name='hydranotificationemaildelivery',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='hyd_not_email_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='hydranotificationemaildelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('attempts', 0), ('lease_expires_at__isnull', True), ('sent_at__isnull', True), ('status', 'pending')), models.Q(('attempts__gte', 1), ('lease_expires_at__isnull', False), ('sent_at__isnull', True), ('status', 'sending')), models.Q(('attempts__gte', 1), ('lease_expires_at__isnull', True), ('next_attempt_at__isnull', False), ('sent_at__isnull', True), ('status', 'failed')), models.Q(('attempts__gte', 1), ('lease_expires_at__isnull', True), ('sent_at__isnull', False), ('status', 'sent')), models.Q(('lease_expires_at__isnull', True), ('sent_at__isnull', True), ('status__in', ('dead', 'not_applicable'))), _connector='OR'), name='hyd_not_email_state_shape'),
        ),
    ]
