# Generated by Django 4.2.24 on 2026-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='children_info',
            field=models.TextField(blank=True, null=True, verbose_name='Children Information'),
        ),
        migrations.AddField(
            model_name='employee',
            name='np_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova Poshta Branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='np_postomat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova Poshta Parcel Locker'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='fop_maintained',
            field=models.BooleanField(default=False, verbose_name='Maintained'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='payment_purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Purpose'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='rnokpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RNOKPP'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='wallet_currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Wallet Currency'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet Number'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Name'),
        ),
    ]
