# Generated by Django 6.0 on 2025-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Work Location'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Work Location'),
        ),
    ]
