# Generated by Django 4.2.24 on 2026-06-20 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employee_children_info_employee_np_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('is_reporting_manager', models.BooleanField(default=False, verbose_name='Use Reporting Manager')),
                ('approver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approver_for', to='employee.employee', verbose_name='Approver')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvers', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Employee Leave Approver',
                'verbose_name_plural': 'Employee Leave Approvers',
                'ordering': ['sequence'],
            },
        ),
    ]
