# Generated by Django 5.2 on 2026-01-19 09:22

import horilla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeworkinformation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='action_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=30, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_profile',
            field=models.ImageField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=50, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='bank_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Bank Name'),
        ),
    ]
