# Generated by Django 5.2 on 2026-03-24 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_actiontype_action_type_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional +).', regex='^\\+?\\d{7,15}$')], verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional +).', regex='^\\+?\\d{7,15}$')], verbose_name='Work Phone'),
        ),
    ]
