# Generated by Django 4.2.24 on 2026-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeleaveapprover'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_ceo',
            field=models.BooleanField(default=False, help_text='Hidden from everyone except HR (admin).', verbose_name='CEO'),
        ),
    ]
