# Generated by Django 5.2 on 2026-03-31 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 characters, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 characters, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')], verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 characters, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')], verbose_name='Work Phone'),
        ),
    ]
