# Generated by Django 4.2.24 on 2026-06-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_knowledgespace_knowledgedocument_knowledgecomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_comments', to='employee.policy', verbose_name='Policy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
