# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_description', models.TextField(blank=True, null=True)),
                ('asset_tracking_id', models.CharField(max_length=30, unique=True)),
                ('asset_purchase_date', models.DateField()),
                ('asset_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_status', models.CharField(choices=[('In use', 'In use'), ('Available', 'Available'), ('Not-Available', 'Not-Available')], default='Available', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.TextField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, choices=[('Minor damage', 'Minor damage'), ('Major damage', 'Major damage'), ('Healthy', 'Healthy')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_category_name', models.CharField(max_length=255, unique=True)),
                ('asset_category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=30, unique=True)),
                ('lot_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_request_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_request_status', models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=30, null=True)),
                ('asset_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory')),
            ],
        ),
    ]
