# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='requested_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_employee', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset_id',
            field=models.ForeignKey(limit_choices_to={'asset_status': 'Available'}, on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_by_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_employeee', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_lot_number_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetlot'),
        ),
    ]
