# Generated by Django 5.2 on 2026-08-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_quantity'),
        ('employee', '0005_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Assigned To'),
        ),
    ]
