# Generated by Django 5.2 on 2026-08-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tracking_id', models.CharField(max_length=30, unique=True, verbose_name='Tracking Id')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In use', 'In Use'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='Available', max_length=20, verbose_name='Status')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='asset.asset', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Asset Item',
                'verbose_name_plural': 'Asset Items',
                'ordering': ['tracking_id'],
            },
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetitem', verbose_name='Asset Item'),
        ),
    ]
