# Generated by Django 4.2.7 on 2024-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('highlight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTrackingFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_fields', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
