# Generated by Django 5.2 on 2026-05-23 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('app_label', models.CharField(max_length=100, verbose_name='App')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('tracked_fields', models.JSONField(blank=True, default=list, help_text='Leave empty to track every field on the model.', verbose_name='Tracked Fields')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Audit Tracking Configuration',
                'verbose_name_plural': 'Audit Tracking Configurations',
                'unique_together': {('app_label', 'model_name')},
            },
        ),
    ]
