# Generated by Django 5.2 on 2026-08-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_companyleaves_options_and_more'),
        ('horilla_audit', '0002_auditmodelconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytrackingfields',
            options={'verbose_name': 'History Tracking Fields', 'verbose_name_plural': 'History Tracking Fields'},
        ),
        migrations.AddField(
            model_name='historytrackingfields',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
