# Generated by Django 5.2 on 2026-01-19 09:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='applicable_for',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('members', 'Members'), ('managers', 'Managers')], max_length=50, null=True, verbose_name='Applicable For'),
        ),
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='bonus_for',
            field=models.CharField(choices=[('completed', 'Completing'), ('Closed', 'Closing')], max_length=25, verbose_name='Bonus For'),
        ),
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='conditions',
            field=models.CharField(blank=True, choices=[('=', '='), ('>', '>'), ('<', '<'), ('<=', '<='), ('>=', '>=')], max_length=25, null=True, verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='field_1',
            field=models.CharField(blank=True, choices=[('complition_date', 'Completion Date')], max_length=25, null=True, verbose_name='Field 1'),
        ),
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='field_2',
            field=models.CharField(blank=True, choices=[('end_date', 'End Date')], max_length=25, null=True, verbose_name='Field 2'),
        ),
        migrations.AlterField(
            model_name='bonuspointsetting',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='employeebonuspoint',
            name='bonus_point',
            field=models.IntegerField(default=0, verbose_name='Bonus Points'),
        ),
        migrations.AlterField(
            model_name='employeekeyresult',
            name='current_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='employeekeyresult',
            name='start_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Start Value'),
        ),
        migrations.AlterField(
            model_name='employeekeyresult',
            name='target_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='historicalemployeekeyresult',
            name='current_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='historicalemployeekeyresult',
            name='start_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Start Value'),
        ),
        migrations.AlterField(
            model_name='historicalemployeekeyresult',
            name='target_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='historicalkeyresult',
            name='progress_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', [('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')])], default='%', max_length=60, verbose_name='Progress Type'),
        ),
        migrations.AlterField(
            model_name='historicalkeyresult',
            name='target_value',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='historicalobjective',
            name='self_employee_progress_update',
            field=models.BooleanField(default=True, verbose_name='Self employee progress update'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='progress_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('#', 'Number'), ('Currency', [('$', 'USD$'), ('₹', 'INR'), ('€', 'EUR')])], default='%', max_length=60, verbose_name='Progress Type'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='target_value',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='question_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pms.questiontemplate', verbose_name='Question Template'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='self_employee_progress_update',
            field=models.BooleanField(default=True, verbose_name='Self employee progress update'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Period Name'),
        ),
    ]
