# Generated by Django 5.2 on 2026-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_bonuspointsetting_applicable_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjective',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
