# Generated by Django 5.2 on 2026-06-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendanceallowedip_company_id_and_more'),
        ('pms', '0003_historicalobjective_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuspointsetting',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
