# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_bonuspointsetting_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Review Period Name'),
        ),
    ]
