# Generated by Django 5.2 on 2026-08-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0012_remove_companyleaves_company_id_and_more'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Marks layouts seeded for standard enterprise reports.', verbose_name='Standard Report Layout'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('company', 'Company'), ('system', 'System')], default='private', max_length=20, verbose_name='Visibility'),
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('report_slug', models.CharField(blank=True, default='', help_text='Leave blank to apply to a whole domain (or all reports).', max_length=100, verbose_name='Report slug')),
                ('domain', models.CharField(blank=True, default='', help_text='workforce, time_leave, payroll, talent, compliance — or blank.', max_length=50, verbose_name='Domain')),
                ('permission', models.CharField(blank=True, default='', help_text='Optional Django permission codename, e.g. employee.view_employee.', max_length=150, verbose_name='Permission')),
                ('can_view', models.BooleanField(default=True, verbose_name='Can view')),
                ('can_export', models.BooleanField(default=True, verbose_name='Can export')),
                ('can_subscribe', models.BooleanField(default=True, verbose_name='Can subscribe')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(blank=True, help_text='Blank = any authenticated user (still subject to permission).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_access_rules', to='auth.group', verbose_name='Group')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Report Access',
                'verbose_name_plural': 'Report Access',
                'ordering': ['report_slug', 'domain', 'group_id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('report_slug', models.CharField(max_length=100, verbose_name='Report')),
                ('name', models.CharField(max_length=150, verbose_name='Subscription Name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, verbose_name='Frequency')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses.', verbose_name='Recipients')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Optional filter overrides (department_id, relative period).', verbose_name='Filters')),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Subscription',
                'verbose_name_plural': 'Report Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('report_slug', models.CharField(max_length=100, verbose_name='Report')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_favorites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report Favorite',
                'verbose_name_plural': 'Report Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('report_slug', 'user', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='ReportFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('report_slug', models.CharField(max_length=100, verbose_name='Report')),
                ('name', models.CharField(max_length=100, verbose_name='Preset Name')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='period_preset, dates, and report-specific filter keys.', verbose_name='Filters')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filter_presets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report Filter Preset',
                'verbose_name_plural': 'Report Filter Presets',
                'ordering': ['name'],
                'unique_together': {('report_slug', 'name', 'user', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='ReportRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('report_slug', models.CharField(max_length=100, verbose_name='Report')),
                ('action', models.CharField(choices=[('view', 'View'), ('export', 'Export'), ('subscribe', 'Subscription')], default='view', max_length=20, verbose_name='Action')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filters')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_run_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report Run Log',
                'verbose_name_plural': 'Report Run Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='report_runlog_user_created'), models.Index(fields=['report_slug', '-created_at'], name='report_runlog_slug_created')],
            },
        ),
        migrations.CreateModel(
            name='ReportSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='View Name')),
                ('report_slugs', models.JSONField(blank=True, default=list, verbose_name='Reports')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_saved_views', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Report Saved View',
                'verbose_name_plural': 'Report Saved Views',
                'ordering': ['name'],
                'unique_together': {('name', 'owner', 'company_id')},
            },
        ),
    ]
