# Generated by Django 4.2.24 on 2026-07-14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "hydra_id",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "passport_name",
                    models.CharField(max_length=255, verbose_name="Passport name"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last name"),
                ),
                (
                    "date_of_birth",
                    models.DateField(verbose_name="Date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=16,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "citizenship",
                    models.CharField(
                        help_text="Two-letter ISO country code.",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Use a two-letter ISO country code, for example "
                                    "UA or PL."
                                ),
                                regex="^[A-Za-z]{2}$",
                            )
                        ],
                        verbose_name="Citizenship",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("pl", "Polish"),
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                            ("en", "English"),
                            ("az", "Azerbaijani"),
                            ("es", "Spanish"),
                            ("fil", "Filipino"),
                            ("id", "Indonesian"),
                            ("ne", "Nepali"),
                        ],
                        default="pl",
                        max_length=3,
                        verbose_name="Preferred language",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?[0-9 ()-]{7,25}$",
                            )
                        ],
                        verbose_name="Phone",
                    ),
                ),
                (
                    "whatsapp_viber",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?[0-9 ()-]{7,25}$",
                            )
                        ],
                        verbose_name="WhatsApp / Viber",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("candidate", "Candidate"),
                            ("onboarding", "Onboarding"),
                            ("employee", "Employee"),
                            ("inactive", "Inactive"),
                        ],
                        default="prospect",
                        max_length=16,
                        verbose_name="Lifecycle state",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hydra_person",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hydra person",
                "verbose_name_plural": "Hydra people",
                "ordering": ("passport_name", "hydra_id"),
                "permissions": (
                    (
                        "link_candidate",
                        "Can link recruitment applications to Hydra person",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="PersonApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_person_link",
                        to="recruitment.candidate",
                        verbose_name="Candidate application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="hydra_people.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person application link",
                "verbose_name_plural": "Person application links",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"], name="hydra_person_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["date_of_birth", "citizenship"],
                name="hydra_person_identity_idx",
            ),
        ),
    ]
