# Generated by Django 4.2.24 on 2026-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personapplication',
            name='link_source',
            field=models.CharField(choices=[('manual', 'Manual link'), ('hydra_intake', 'Hydra intake'), ('backfill', 'Backfill')], default='manual', max_length=16, verbose_name='Link source'),
        ),
    ]
