# Generated by Django 4.2.24 on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydra_people", "0002_personapplication_link_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ("passport_name", "hydra_id"),
                "permissions": (
                    (
                        "link_candidate",
                        "Can link recruitment applications to Hydra person",
                    ),
                    (
                        "convert_person_to_employee",
                        "Can convert Hydra person to Horilla employee",
                    ),
                ),
                "verbose_name": "Hydra person",
                "verbose_name_plural": "Hydra people",
            },
        ),
        migrations.CreateModel(
            name="EmployeeConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("hydra_operator", "Hydra operator"),
                            ("horilla_onboarding", "Horilla onboarding"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_snapshot", models.JSONField()),
                ("field_decisions", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_employee_conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_employee_conversion",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_conversion",
                        to="employee.employee",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_conversion",
                        to="hydra_people.person",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "default_permissions": (),
                "permissions": (
                    (
                        "view_employeeconversion",
                        "Can view employee conversion history",
                    ),
                ),
            },
        ),
        migrations.AddIndex(
            model_name="employeeconversion",
            index=models.Index(
                fields=["occurred_at"],
                name="hyd_people_conv_time_idx",
            ),
        ),
    ]
