# Generated by Django 4.2.24 on 2026-07-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_transition_rules(apps, schema_editor):
    Stage = apps.get_model('recruitment', 'Stage')
    Rule = apps.get_model('hydra_people', 'RecruitmentStageTransitionRule')
    recruitment_ids = Stage.objects.filter(is_active=True).values_list(
        'recruitment_id', flat=True
    ).distinct()
    for recruitment_id in recruitment_ids:
        stages = list(
            Stage.objects.filter(
                recruitment_id=recruitment_id,
                is_active=True,
            ).order_by('sequence', 'pk')
        )
        for from_stage in stages:
            from_sequence = from_stage.sequence or 0
            for to_stage in stages:
                if from_stage.pk == to_stage.pk:
                    continue
                to_sequence = to_stage.sequence or 0
                Rule.objects.get_or_create(
                    recruitment_id=recruitment_id,
                    from_stage_id=from_stage.pk,
                    to_stage_id=to_stage.pk,
                    defaults={
                        'requires_reason': (
                            to_stage.stage_type == 'cancelled'
                            or to_sequence <= from_sequence
                            or abs(to_sequence - from_sequence) > 1
                        ),
                        'requires_schedule_date': False,
                        'requires_joining_date': to_stage.stage_type == 'hired',
                        'allow_override': True,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
        ('hydra_people', '0003_employee_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStageTransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('requires_reason', models.BooleanField(default=False)),
                ('requires_schedule_date', models.BooleanField(default=False)),
                ('requires_joining_date', models.BooleanField(default=False)),
                ('allow_override', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_transition_rules_from', to='recruitment.stage')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_transition_rules', to='recruitment.recruitment')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_transition_rules_to', to='recruitment.stage')),
            ],
            options={
                'ordering': ('recruitment_id', 'from_stage__sequence', 'to_stage__sequence'),
                'permissions': (('override_recruitment_transition', 'Can override recruitment transition requirements'),),
            },
        ),
        migrations.CreateModel(
            name='CandidateStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hydra', 'Hydra'), ('horilla_pipeline', 'Horilla pipeline')], max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('override', models.BooleanField(default=False)),
                ('requirements_snapshot', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_candidate_stage_transitions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_stage_transitions', to='recruitment.candidate')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_candidate_transitions_from', to='recruitment.stage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_events', to='hydra_people.recruitmentstagetransitionrule')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_candidate_transitions_to', to='recruitment.stage')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='recruitmentstagetransitionrule',
            constraint=models.UniqueConstraint(fields=('recruitment', 'from_stage', 'to_stage'), name='hyd_people_rule_pair_uniq'),
        ),
        migrations.AddIndex(
            model_name='candidatestagetransition',
            index=models.Index(fields=['candidate', 'occurred_at'], name='hyd_people_trans_time_idx'),
        ),
        migrations.RunPython(seed_transition_rules, migrations.RunPython.noop),
    ]
