# Generated by Django 4.2.24 on 2026-07-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from hashlib import sha256
from itertools import combinations
import re
import unicodedata
import uuid


def _normalize_text(value):
    return " ".join(unicodedata.normalize("NFKC", str(value or "")).casefold().split())


def _normalize_phone(value):
    return "".join(re.findall(r"\d", unicodedata.normalize("NFKC", str(value or ""))))


def _digest(parts):
    value = "\x1f".join(str(part) for part in parts)
    return sha256(value.encode("utf-8")).hexdigest() if value.strip("\x1f") else ""


def backfill_identity_fingerprints_and_suggestions(apps, schema_editor):
    Person = apps.get_model("hydra_people", "Person")
    Suggestion = apps.get_model("hydra_people", "PersonDuplicateSuggestion")
    people = list(Person.objects.order_by("pk"))
    groups = {
        "identity_exact": {},
        "passport_dob": {},
        "email_exact": {},
        "phone_exact": {},
    }
    for person in people:
        dob = person.date_of_birth.isoformat() if person.date_of_birth else ""
        identity_parts = (
            _normalize_text(person.first_name),
            _normalize_text(person.last_name),
            dob,
            _normalize_text(person.citizenship),
        )
        passport_parts = (_normalize_text(person.passport_name), dob)
        email = _normalize_text(person.email)
        phone = _normalize_phone(person.phone)
        messenger = _normalize_phone(person.whatsapp_viber)
        person.identity_fingerprint = _digest(identity_parts)
        person.passport_dob_fingerprint = _digest(passport_parts)
        person.email_fingerprint = _digest((email,)) if email else ""
        person.phone_fingerprint = _digest((phone,)) if phone else ""
        person.messenger_fingerprint = _digest((messenger,)) if messenger else ""
        for reason, key in (
            ("identity_exact", identity_parts),
            ("passport_dob", passport_parts),
            ("email_exact", email),
        ):
            if key and (not isinstance(key, tuple) or all(key)):
                groups[reason].setdefault(key, []).append(person.pk)
        for number in {phone, messenger} - {""}:
            groups["phone_exact"].setdefault(number, []).append(person.pk)
    Person.objects.bulk_update(
        people,
        (
            "identity_fingerprint",
            "passport_dob_fingerprint",
            "email_fingerprint",
            "phone_fingerprint",
            "messenger_fingerprint",
        ),
        batch_size=500,
    )
    pair_reasons = {}
    for reason, reason_groups in groups.items():
        for person_ids in reason_groups.values():
            for low_id, high_id in combinations(sorted(set(person_ids)), 2):
                pair_reasons.setdefault((low_id, high_id), []).append(reason)
    weights = {
        "identity_exact": 100,
        "passport_dob": 90,
        "email_exact": 65,
        "phone_exact": 60,
    }
    now = django.utils.timezone.now()
    suggestions = []
    for (low_id, high_id), reasons in pair_reasons.items():
        ordered_reasons = [
            reason
            for reason in weights
            if reason in reasons
        ]
        reason_weights = sorted((weights[reason] for reason in ordered_reasons), reverse=True)
        score = min(100, reason_weights[0] + 5 * (len(reason_weights) - 1))
        suggestions.append(
            Suggestion(
                person_low_id=low_id,
                person_high_id=high_id,
                score=score,
                match_reasons=ordered_reasons,
                state="open",
                last_evaluated_at=now,
            )
        )
    Suggestion.objects.bulk_create(suggestions, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_people', '0004_recruitmentstagetransitionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDuplicateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('match_reasons', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('stale', 'No longer matches'), ('merged', 'Merged')], default='open', max_length=16)),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-score', 'created_at', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='PersonMergeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('match_reasons', models.JSONField()),
                ('field_decisions', models.JSONField()),
                ('moved_reference_counts', models.JSONField()),
                ('preserved_source_identifiers', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_personmergeevent', 'Can view Person merge evidence'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PersonMergeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_kind', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('relation_kind', 'object_id', 'pk'),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('passport_name', 'hydra_id'), 'permissions': (('link_candidate', 'Can link recruitment applications to Hydra person'), ('review_person_duplicates', 'Can review Hydra Person duplicate suggestions'), ('dismiss_person_duplicate', 'Can dismiss Person duplicate suggestions'), ('merge_person', 'Can merge duplicate Hydra Person records'), ('convert_person_to_employee', 'Can convert Hydra person to Horilla employee')), 'verbose_name': 'Hydra person', 'verbose_name_plural': 'Hydra people'},
        ),
        migrations.AddField(
            model_name='person',
            name='email_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='identity_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='merged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='merged_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_person_merges_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_sources', to='hydra_people.person', verbose_name='Canonical Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='messenger_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_dob_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('merged_at__isnull', True), ('merged_by__isnull', True), ('merged_into__isnull', True)), models.Q(('is_active', False), ('lifecycle_state', 'inactive'), ('merged_at__isnull', False), ('merged_by__isnull', False), ('merged_into__isnull', False)), _connector='OR'), name='hyd_person_merge_shape'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('merged_into__isnull', True), models.Q(('merged_into_id', models.F('pk')), _negated=True), _connector='OR'), name='hyd_person_not_self_merge'),
        ),
        migrations.AddField(
            model_name='personmergereference',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moved_references', to='hydra_people.personmergeevent'),
        ),
        migrations.AddField(
            model_name='personmergeevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_person_merge_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personmergeevent',
            name='duplicate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merge_event_as_duplicate', to='hydra_people.person'),
        ),
        migrations.AddField(
            model_name='personmergeevent',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_events_as_survivor', to='hydra_people.person'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='merge_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestion', to='hydra_people.personmergeevent'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='person_high',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_suggestions_as_high', to='hydra_people.person'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='person_low',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_suggestions_as_low', to='hydra_people.person'),
        ),
        migrations.AddField(
            model_name='personduplicatesuggestion',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_duplicate_suggestions_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='personmergereference',
            constraint=models.UniqueConstraint(fields=('event', 'relation_kind', 'object_id'), name='hyd_person_merge_ref_uniq'),
        ),
        migrations.AddIndex(
            model_name='personmergeevent',
            index=models.Index(fields=['survivor', 'occurred_at'], name='hyd_person_merge_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='personduplicatesuggestion',
            constraint=models.UniqueConstraint(fields=('person_low', 'person_high'), name='hyd_person_dup_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='personduplicatesuggestion',
            constraint=models.CheckConstraint(check=models.Q(('person_low_id__lt', models.F('person_high_id'))), name='hyd_person_dup_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='personduplicatesuggestion',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 100)), name='hyd_person_dup_score_range'),
        ),
        migrations.RunPython(
            backfill_identity_fingerprints_and_suggestions,
            migrations.RunPython.noop,
        ),
    ]
