blank_issues_enabled: false
contact_links:
  - name: Horilla Community Support
    url: https://github.com/horilla-opensource/horilla/discussions
    about: Ask questions or discuss features here
  - name: Documentation
    url: https://horilla-opensource.github.io/horilla-docs/
    about: Check the official Horilla documentation