# Generated by Django 5.2 on 2026-07-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_setupchecklistdismissal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(help_text="Stable identifier used in code/seed data, e.g. 'getting-started'.", max_length=120, verbose_name='Key')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('page_match', models.CharField(blank=True, default='', help_text="Where this tour applies. With 'URL name' enter the resolver name (e.g. 'dashboard'); with 'Path starts with' enter a path prefix (e.g. '/employee/'). Leave blank to allow on any page.", max_length=200, verbose_name='Page')),
                ('match_type', models.CharField(choices=[('url_name', 'URL name (exact)'), ('path_prefix', 'Path starts with')], default='url_name', max_length=20, verbose_name='Match by')),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('admins', 'Admins / Superusers'), ('managers', 'Reporting managers'), ('employees', 'Employees (non-managers)')], default='all', max_length=20, verbose_name='Audience')),
                ('trigger', models.CharField(choices=[('auto_once', 'Auto-start once, then on demand'), ('manual', 'Only from the Help launcher')], default='auto_once', max_length=20, verbose_name='Trigger')),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished tours are drafts and never shown to users.', verbose_name='Published')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority tours auto-start first when several match a page.', verbose_name='Priority')),
                ('show_progress', models.BooleanField(default=True, verbose_name='Show progress bar')),
                ('allow_close', models.BooleanField(default=True, verbose_name='Allow close')),
                ('icon', models.CharField(blank=True, default='map-outline', help_text='ion-icon name shown in the Help launcher.', max_length=60, verbose_name='Icon')),
                ('company_id', models.ForeignKey(blank=True, help_text='Leave blank for a global tour shared by every company.', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TourStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sequence', models.IntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('element_selector', models.CharField(blank=True, default='', help_text="CSS selector of the element to highlight (e.g. '#notificationIcon'). Leave blank for a centered message step.", max_length=255, verbose_name='Element selector')),
                ('side', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('over', 'Center (no element)')], default='bottom', max_length=10, verbose_name='Position')),
                ('align', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='start', max_length=10, verbose_name='Align')),
                ('page_match', models.CharField(blank=True, default='', help_text="Optional: for multi-page tours, the URL name this step lives on. Leave blank to use the tour's page.", max_length=200, verbose_name='Step page')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='horilla_tour.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour step',
                'verbose_name_plural': 'Tour steps',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='in_progress', max_length=20, verbose_name='Status')),
                ('last_step', models.IntegerField(default=0, verbose_name='Last step index')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='horilla_tour.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tour progress',
                'verbose_name_plural': 'Tour progress',
                'unique_together': {('tour', 'user')},
            },
        ),
    ]
