# Generated by Django 5.2 on 2026-08-19 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horilla_tour", "0087_seed_faq_view_tour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourStepTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English (US)"),
                            ("de", "Deutsch"),
                            ("es", "Español"),
                            ("fr", "Français"),
                            ("ar", "العربية"),
                            ("pt-br", "Português (Brasil)"),
                            ("zh-hans", "简体中文"),
                            ("zh-hant", "繁體中文"),
                            ("it", "Italian"),
                            ("tr", "Turkish"),
                            ("uk", "Українська"),
                            ("ro", "Română"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "tour_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="horilla_tour.tourstep",
                        verbose_name="Tour step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour step translation",
                "verbose_name_plural": "Tour step translations",
                "unique_together": {("tour_step", "language")},
            },
        ),
        migrations.CreateModel(
            name="TourTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English (US)"),
                            ("de", "Deutsch"),
                            ("es", "Español"),
                            ("fr", "Français"),
                            ("ar", "العربية"),
                            ("pt-br", "Português (Brasil)"),
                            ("zh-hans", "简体中文"),
                            ("zh-hant", "繁體中文"),
                            ("it", "Italian"),
                            ("tr", "Turkish"),
                            ("uk", "Українська"),
                            ("ro", "Română"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="horilla_tour.tour",
                        verbose_name="Tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour translation",
                "verbose_name_plural": "Tour translations",
                "unique_together": {("tour", "language")},
            },
        ),
    ]
