# Generated by Django 5.2 on 2026-05-20 05:42

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'flatpages/default.html'", max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Only ACTIVE templates are served by the DB template loader.', max_length=20, verbose_name='state')),
                ('language', models.CharField(blank=True, db_index=True, help_text="Optional language code (e.g. 'ar', 'fr'). Leave blank for all languages.", max_length=10, verbose_name='language')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags. E.g. 'email,onboarding,pdf'", max_length=255, verbose_name='tags')),
                ('active_from', models.DateTimeField(blank=True, help_text='Serve this template only after this datetime. Leave blank = no restriction.', null=True, verbose_name='active from')),
                ('active_until', models.DateTimeField(blank=True, help_text='Stop serving this template after this datetime. Leave blank = no restriction.', null=True, verbose_name='active until')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Locked At')),
                ('access_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Access Count')),
                ('last_accessed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Accessed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_locked', to=settings.AUTH_USER_MODEL, verbose_name='Locked By')),
                ('sites', models.ManyToManyField(blank=True, related_name='horilla_dbtemplate_templates', to='sites.site', verbose_name='sites')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('sites')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(db_index=True, verbose_name='version')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='state')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='horilla_dbtemplate.template', verbose_name='template')),
            ],
            options={
                'verbose_name': 'Template Version',
                'verbose_name_plural': 'Template Versions',
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='horilla_dbtemplate_unique_template_version')],
            },
        ),
    ]
