# Generated by Django 4.2.24 on 2026-07-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("code", models.CharField(max_length=64, verbose_name="Stable code")),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                ("language", models.CharField(choices=[("pl", "Polish"), ("uk", "Ukrainian"), ("ru", "Russian"), ("en", "English")], default="pl", max_length=3, verbose_name="Language")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body", models.TextField(max_length=10000, verbose_name="Plain-text body")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hydra_message_templates", to="base.company", verbose_name="Company")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
            ],
            options={
                "ordering": ("company__company", "code", "language", "pk"),
                "permissions": (("export_template_data", "Can export scoped Szablonizator data"),),
                "indexes": [models.Index(fields=["company", "is_active"], name="hyd_tpl_company_active_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code", "language"), name="hyd_tpl_company_code_lang_uniq")],
            },
        ),
        migrations.CreateModel(
            name="TemplateDataExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                ("row_count", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("filters", models.JSONField(default=dict)),
                ("scope_company_ids", models.JSONField(default=list)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hydra_template_data_exports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "default_permissions": (),
                "permissions": (("view_templatedataexport", "Can view template data export audit"),),
                "indexes": [models.Index(fields=["actor", "occurred_at"], name="hyd_tpl_export_actor_idx")],
            },
        ),
    ]
