# Generated by Django 4.2.24 on 2026-07-17 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_people', '0005_person_duplicate_merge'),
        ('hydra_coordination', '0004_organizationaccessevent_and_more'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('default_language', models.CharField(choices=[('pl', 'Polish'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('en', 'English'), ('az', 'Azerbaijani'), ('es', 'Spanish'), ('fil', 'Filipino'), ('id', 'Indonesian'), ('ne', 'Nepali')], default='pl', max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_courses', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('company__company', 'code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('rule', 'Automatic rule'), ('manual', 'Manual')], max_length=12)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='assigned', editable=False, max_length=16)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assignment_snapshot', models.JSONField(editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('assigned_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hydra_courses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_assignments', to='base.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hydra_onboarding.course')),
            ],
            options={
                'ordering': ('status', 'due_at', 'assigned_at', 'pk'),
                'permissions': (('assign_course', 'Can assign Hydra onboarding courses'), ('start_courseassignment', 'Can start a Hydra course assignment'), ('confirm_courseassignment', 'Can confirm Hydra course completion'), ('submit_quizattempt', 'Can submit Hydra course quiz attempts')),
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('en', 'English'), ('az', 'Azerbaijani'), ('es', 'Spanish'), ('fil', 'Filipino'), ('id', 'Indonesian'), ('ne', 'Nepali')], max_length=3)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', editable=False, max_length=12)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('content_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hydra_onboarding.course')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_hydra_course_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course_id', 'language', '-version_number', 'pk'),
                'permissions': (('publish_courseversion', 'Can publish a Hydra course version'),),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('passing_score', models.PositiveSmallIntegerField(default=80)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('course_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='hydra_onboarding.courseversion')),
            ],
            options={
                'ordering': ('course_version_id',),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('prompt', models.TextField(max_length=1000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='hydra_onboarding.quiz')),
            ],
            options={
                'ordering': ('quiz_id', 'sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='hydra_onboarding.quizquestion')),
            ],
            options={
                'ordering': ('question_id', 'sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('passed', models.BooleanField()),
                ('answers_snapshot', models.JSONField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='hydra_onboarding.courseassignment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='hydra_onboarding.quiz')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('assignment_id', 'sequence', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='hydra_onboarding.courseversion')),
            ],
            options={
                'ordering': ('course_version_id', 'sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CourseConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statement', models.CharField(max_length=500)),
                ('statement_snapshot', models.JSONField()),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='hydra_onboarding.courseassignment')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-confirmed_at', '-pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='CourseAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('language', models.CharField(blank=True, choices=[('pl', 'Polish'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('en', 'English'), ('az', 'Azerbaijani'), ('es', 'Spanish'), ('fil', 'Filipino'), ('id', 'Indonesian'), ('ne', 'Nepali')], max_length=3)),
                ('due_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_assignment_rules', to='base.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='hydra_onboarding.course')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_assignment_rules', to='base.department')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_assignment_rules', to='base.employeetype')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_assignment_rules', to='hydra_coordination.location')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_assignment_rules', to='hydra_coordination.team')),
            ],
            options={
                'ordering': ('-priority', 'course__code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CourseAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('assigned', 'Course assigned'), ('started', 'Course started'), ('quiz_submitted', 'Quiz submitted'), ('completed', 'Course completed')], max_length=20)),
                ('source', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=8)),
                ('details_snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_course_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hydra_onboarding.courseassignment')),
                ('confirmation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_event', to='hydra_onboarding.courseconfirmation')),
                ('quiz_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_event', to='hydra_onboarding.quizattempt')),
            ],
            options={
                'ordering': ('assignment_id', 'sequence', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hydra_onboarding.courseversion'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='hydra_people.person'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hydra_onboarding.courseassignmentrule'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'sequence'), name='hyd_onb_question_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_onb_question_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='quizoption',
            constraint=models.UniqueConstraint(fields=('question', 'sequence'), name='hyd_onb_option_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quizoption',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_onb_option_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('assignment', 'sequence'), name='hyd_onb_attempt_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_onb_attempt_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='hyd_onb_attempt_score'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(check=models.Q(('passing_score__gte', 1), ('passing_score__lte', 100)), name='hyd_onb_quiz_passing_score'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 20)), name='hyd_onb_quiz_max_attempts'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course_version', 'sequence'), name='hyd_onb_lesson_sequence'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_onb_lesson_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(('estimated_minutes__gte', 1), ('estimated_minutes__lte', 480)), name='hyd_onb_lesson_minutes'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'language', 'version_number'), name='hyd_onb_version_identity'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.CheckConstraint(check=models.Q(('version_number__gte', 1)), name='hyd_onb_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('content_fingerprint', ''), ('published_at__isnull', True), ('published_by__isnull', True), ('status', 'draft')), models.Q(('content_fingerprint__gt', ''), ('published_at__isnull', False), ('published_by__isnull', False), ('status__in', ('published', 'retired'))), _connector='OR'), name='hyd_onb_version_publish_shape'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentrule',
            constraint=models.CheckConstraint(check=models.Q(('priority__lte', 1000)), name='hyd_onb_rule_priority'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentrule',
            constraint=models.CheckConstraint(check=models.Q(('due_days__isnull', True), models.Q(('due_days__gte', 1), ('due_days__lte', 365)), _connector='OR'), name='hyd_onb_rule_due_days'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentevent',
            constraint=models.UniqueConstraint(fields=('assignment', 'sequence'), name='hyd_onb_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentevent',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='hyd_onb_event_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', False), ('source', 'user')), models.Q(('actor__isnull', True), ('source', 'system')), _connector='OR'), name='hyd_onb_event_actor_shape'),
        ),
        migrations.AddConstraint(
            model_name='courseassignmentevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ('assigned', 'started')), ('confirmation__isnull', True), ('quiz_attempt__isnull', True)), models.Q(('action', 'quiz_submitted'), ('confirmation__isnull', True), ('quiz_attempt__isnull', False)), models.Q(('action', 'completed'), ('confirmation__isnull', False), ('quiz_attempt__isnull', True)), _connector='OR'), name='hyd_onb_event_subject_shape'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['company', 'status', 'due_at'], name='hyd_onb_assign_state_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['person', 'status'], name='hyd_onb_assign_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('person', 'course'), name='hyd_onb_person_course_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='hyd_onb_assign_version'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', True), ('started_at__isnull', True), ('status', 'assigned')), models.Q(('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('started_at__isnull', False), ('status', 'completed')), _connector='OR'), name='hyd_onb_assign_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rule__isnull', False), ('source', 'rule')), models.Q(('rule__isnull', True), ('source', 'manual')), _connector='OR'), name='hyd_onb_assign_source_shape'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='hyd_onb_course_company_code'),
        ),
    ]
