# Generated by Django 4.2.24 on 2026-07-14

import django.db.models.deletion
import hydra_documents.models
import hydra_documents.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hydra_people", "0002_personapplication_link_source"),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("category", models.CharField(choices=[("identity", "Identity"), ("recruitment", "Recruitment"), ("other", "Other")], default="other", max_length=20)),
                ("file", models.FileField(max_length=255, storage=hydra_documents.storage.PrivateDocumentStorage(base_url=None), upload_to=hydra_documents.models.private_document_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("verified_content_type", models.CharField(max_length=50)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(editable=False, max_length=64)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hydra_private_documents", to="recruitment.candidate")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="private_documents", to="hydra_people.person")),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "permissions": (("download_privatedocument", "Can download private document"),),
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_uuid", models.UUIDField()),
                ("action", models.CharField(choices=[("upload", "Upload"), ("download", "Download")], max_length=16)),
                ("outcome", models.CharField(choices=[("allowed", "Allowed"), ("denied", "Denied"), ("not_found", "Not found"), ("error", "Error")], max_length=16)),
                ("reason", models.CharField(max_length=48)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent_sha256", models.CharField(blank=True, max_length=64)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="hydra_document_access_logs", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="access_logs", to="hydra_documents.privatedocument")),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "permissions": (("view_documentaccesslog", "Can view document access log"),),
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(model_name="privatedocument", index=models.Index(fields=["candidate", "created_at"], name="hydra_doc_candidate_idx")),
        migrations.AddIndex(model_name="privatedocument", index=models.Index(fields=["person", "created_at"], name="hydra_doc_person_idx")),
        migrations.AddIndex(model_name="documentaccesslog", index=models.Index(fields=["document_uuid", "occurred_at"], name="hydra_doc_access_idx")),
        migrations.AddIndex(model_name="documentaccesslog", index=models.Index(fields=["actor", "occurred_at"], name="hydra_doc_actor_idx")),
    ]
