# Generated by Django 4.2.24 on 2026-07-15 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hydra_documents.models
import hydra_documents.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_people', '0003_employee_conversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
        ('hydra_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatedocument',
            options={'ordering': ('-created_at', '-pk'), 'permissions': (('download_privatedocument', 'Can download private document'), ('manage_privatedocumenthold', 'Can manage private document legal hold'))},
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_private_documents_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='deletion_reason',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='file_purged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='legal_hold_applied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='legal_hold_applied_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_document_holds_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='legal_hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='retention_until',
            field=models.DateField(db_index=True, default=hydra_documents.models.default_retention_until),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='scanned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='scanner',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('scan', 'Scan'), ('legal_hold', 'Legal hold'), ('delete', 'Delete')], max_length=16),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=hydra_documents.storage.PrivateDocumentStorage(base_url=None), upload_to=hydra_documents.models.private_document_path),
        ),
        migrations.CreateModel(
            name='QuarantinedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(blank=True, max_length=255, storage=hydra_documents.storage.QuarantineStorage(base_url=None), upload_to=hydra_documents.models.quarantined_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('verified_content_type', models.CharField(max_length=50)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending scan'), ('infected', 'Threat detected'), ('error', 'Scan error'), ('promoted', 'Promoted')], default='pending', max_length=16)),
                ('scanner', models.CharField(blank=True, editable=False, max_length=80)),
                ('scanner_result', models.CharField(blank=True, editable=False, max_length=160)),
                ('scan_completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('purge_after', models.DateTimeField(db_index=True)),
                ('purged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_quarantined_uploads', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_quarantined_uploads', to='recruitment.candidate')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_records', to='hydra_documents.privatedocument')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantined_uploads', to='hydra_people.person')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': (('view_quarantinedupload', 'Can view quarantined upload'),),
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'purge_after'], name='hydra_doc_quarantine_idx')],
            },
        ),
    ]
