# Generated by Django 4.2.24 on 2026-07-16 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hydra_documents.models
import uuid


def seed_document_types_and_backfill(apps, schema_editor):
    DocumentType = apps.get_model("hydra_documents", "PrivateDocumentType")
    PrivateDocument = apps.get_model("hydra_documents", "PrivateDocument")
    allowed = ["application/pdf", "image/jpeg", "image/png"]
    definitions = (
        ("passport", "Passport", "identity", True, True),
        ("identity-document", "Identity document", "identity", False, True),
        ("recruitment-document", "Recruitment document", "recruitment", False, False),
        ("legalization-document", "Legalization document", "legalization", False, False),
        ("other-document", "Other private document", "other", False, False),
    )
    types = {}
    for code, name, category, requires_expiry, single_current in definitions:
        document_type, _ = DocumentType.objects.get_or_create(
            company_id=None,
            code=code,
            defaults={
                "name": name,
                "category": category,
                "allowed_content_types": allowed,
                "max_size_bytes": 10 * 1024 * 1024,
                "retention_days": 365,
                "requires_expiry_date": requires_expiry,
                "single_current": single_current,
                "is_active": True,
            },
        )
        types[code] = document_type

    category_codes = {
        "identity": "identity-document",
        "recruitment": "recruitment-document",
        "legalization": "legalization-document",
        "other": "other-document",
    }
    for document in PrivateDocument.objects.order_by("pk").iterator(chunk_size=500):
        document_type = types[category_codes.get(document.category, "other-document")]
        document.document_type_id = document_type.pk
        document.lineage_uuid = document.uuid
        document.version_number = 1
        document.type_rules_snapshot = {
            "type_uuid": str(document_type.uuid),
            "code": document_type.code,
            "name": document_type.name,
            "category": document_type.category,
            "company_id": None,
            "allowed_content_types": allowed,
            "max_size_bytes": document_type.max_size_bytes,
            "retention_days": document_type.retention_days,
            "requires_expiry_date": document_type.requires_expiry_date,
            "single_current": document_type.single_current,
        }
        document.save(
            update_fields=(
                "document_type",
                "lineage_uuid",
                "version_number",
                "type_rules_snapshot",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydra_documents', '0002_alter_privatedocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('recruitment', 'Recruitment'), ('legalization', 'Legalization'), ('other', 'Other')], default='other', max_length=20)),
                ('allowed_content_types', models.JSONField(default=hydra_documents.models.default_allowed_content_types)),
                ('max_size_bytes', models.PositiveBigIntegerField(default=hydra_documents.models.default_type_max_bytes)),
                ('retention_days', models.PositiveIntegerField(default=hydra_documents.models.default_type_retention_days)),
                ('requires_expiry_date', models.BooleanField(default=False)),
                ('single_current', models.BooleanField(default=True, help_text='Require an existing current version to be explicitly replaced.')),
            ],
            options={
                'ordering': ('company__company', 'name', 'pk'),
            },
        ),
        migrations.AlterModelOptions(
            name='privatedocument',
            options={'ordering': ('-created_at', '-pk'), 'permissions': (('download_privatedocument', 'Can download private document'), ('manage_privatedocumenthold', 'Can manage private document legal hold'), ('replace_privatedocument', 'Can upload a replacement document version'))},
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='expires_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='lineage_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='replacement_reason',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='replaces',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='hydra_documents.privatedocument'),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='type_rules_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='version_number',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='quarantinedupload',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_quarantine_records', to='hydra_documents.privatedocument'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='category',
            field=models.CharField(choices=[('identity', 'Identity'), ('recruitment', 'Recruitment'), ('legalization', 'Legalization'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='privatedocument',
            index=models.Index(fields=['lineage_uuid', 'version_number'], name='hydra_doc_lineage_idx'),
        ),
        migrations.AddConstraint(
            model_name='privatedocument',
            constraint=models.UniqueConstraint(fields=('lineage_uuid', 'version_number'), name='hydra_doc_lineage_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='privatedocument',
            constraint=models.CheckConstraint(check=models.Q(('version_number__gte', 1)), name='hydra_doc_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='privatedocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('replaces__isnull', True), ('version_number', 1)), models.Q(('replaces__isnull', False), ('version_number__gt', 1)), _connector='OR'), name='hydra_doc_version_shape'),
        ),
        migrations.AddConstraint(
            model_name='privatedocument',
            constraint=models.CheckConstraint(check=models.Q(('replaces__isnull', True), models.Q(('replaces_id', models.F('pk')), _negated=True), _connector='OR'), name='hydra_doc_no_self_replace'),
        ),
        migrations.AddField(
            model_name='privatedocumenttype',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave empty only for a global system type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_private_document_types', to='base.company'),
        ),
        migrations.AddField(
            model_name='privatedocumenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='privatedocumenttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hydra_documents.privatedocumenttype'),
        ),
        migrations.AddField(
            model_name='quarantinedupload',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_records', to='hydra_documents.privatedocumenttype'),
        ),
        migrations.AddIndex(
            model_name='privatedocument',
            index=models.Index(fields=['candidate', 'document_type', 'version_number'], name='hydra_doc_type_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='privatedocumenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='hydra_doc_type_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='privatedocumenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='hydra_doc_type_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='privatedocumenttype',
            constraint=models.CheckConstraint(check=models.Q(('max_size_bytes__gt', 0)), name='hydra_doc_type_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='privatedocumenttype',
            constraint=models.CheckConstraint(check=models.Q(('retention_days__gt', 0)), name='hydra_doc_type_retention_positive'),
        ),
        migrations.RunPython(
            seed_document_types_and_backfill,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hydra_documents.privatedocumenttype'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='lineage_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
