# Generated by Django 4.2.24 on 2026-07-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0002_initial"),
        ("hydra_people", "0002_personapplication_link_source"),
        ("recruitment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(editable=False, max_length=64)),
                (
                    "fingerprint",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready to apply"),
                            ("blocked", "Blocked"),
                            ("applied", "Applied"),
                        ],
                        default="blocked",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0, editable=False)),
                ("valid_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "duplicate_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("error_count", models.PositiveIntegerField(default=0, editable=False)),
                ("applied_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_candidate_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_candidate_imports",
                        to="base.jobposition",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_candidate_imports",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "permissions": (("import_candidate", "Can preview and apply candidate imports"),),
            },
        ),
        migrations.CreateModel(
            name="CandidateImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("error", "Error"),
                            ("duplicate", "Duplicate"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, max_length=2000)),
                ("duplicate_reason", models.TextField(blank=True, max_length=1000)),
                ("source_row_hash", models.CharField(editable=False, max_length=64)),
                ("passport_name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=16)),
                ("citizenship", models.CharField(blank=True, max_length=2)),
                ("preferred_language", models.CharField(blank=True, max_length=3)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=25)),
                ("whatsapp_viber", models.CharField(blank=True, max_length=25)),
                ("candidate_mobile", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_candidate",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_import_rows",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "created_person",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_import_rows",
                        to="hydra_people.person",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="hydra_imports.candidateimportsession",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number", "pk"),
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="candidateimportrow",
            constraint=models.UniqueConstraint(
                fields=("session", "row_number"),
                name="hydra_imp_session_row_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateimportrow",
            index=models.Index(
                fields=["session", "outcome"], name="hydra_imp_row_outcome_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateimportsession",
            index=models.Index(
                fields=["created_by", "status"], name="hydra_imp_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateimportsession",
            index=models.Index(
                fields=["recruitment", "status"], name="hydra_imp_recruit_status_idx"
            ),
        ),
    ]
