# Generated by Django 4.2.24 on 2026-07-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def create_default_arrival_link(apps, schema_editor):
    PublicHydraLink = apps.get_model("hydra_links", "PublicHydraLink")
    PublicHydraLink.objects.get_or_create(
        kind="arrival",
        location=None,
        defaults={
            "label": "Arrival to work",
            "base_url": "https://oleksandrkiris.github.io/przyjazd-do-pracy/?v=share-check-2",
            "order": 10,
            "is_active": True,
        },
    )


def remove_default_arrival_link(apps, schema_editor):
    PublicHydraLink = apps.get_model("hydra_links", "PublicHydraLink")
    PublicHydraLink.objects.filter(
        kind="arrival",
        location=None,
        base_url="https://oleksandrkiris.github.io/przyjazd-do-pracy/?v=share-check-2",
    ).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hydra_coordination", "0003_alter_location_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="PublicHydraLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(choices=[("arrival", "Arrival guidance"), ("training", "Location training")], max_length=16)),
                ("label", models.CharField(max_length=120, verbose_name="Public label")),
                ("base_url", models.URLField(max_length=500, verbose_name="Public HTTPS URL")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Order")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="public_hydra_links", to="hydra_coordination.location", verbose_name="Location")),
                ("modified_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_modified_by", to=settings.AUTH_USER_MODEL, verbose_name="Modified By")),
            ],
            options={
                "ordering": ("kind", "order", "location__name", "label", "pk"),
                "permissions": (("manage_global_publichydralink", "Can manage global Hydra public links"),),
                "indexes": [models.Index(fields=["location", "is_active"], name="hyd_link_location_active_idx")],
                "constraints": [
                    models.CheckConstraint(check=Q(("kind", "arrival"), ("location__isnull", True), _connector="AND") | Q(("kind", "training"), ("location__isnull", False), _connector="AND"), name="hyd_link_kind_location_valid"),
                    models.UniqueConstraint(condition=Q(("location__isnull", True)), fields=("kind",), name="hyd_link_global_kind_uniq"),
                    models.UniqueConstraint(condition=Q(("location__isnull", False)), fields=("kind", "location"), name="hyd_link_location_kind_uniq"),
                ],
            },
        ),
        migrations.RunPython(create_default_arrival_link, remove_default_arrival_link),
    ]
