# Generated by Django 4.2.24 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('cafeteria_benefits', 'Cafeteria Benefits'), ('learning', 'Learning'), ('foreign_language', 'Foreign Language')], max_length=32, null=True, verbose_name='Reimbursement sub type'),
        ),
    ]
