# Generated by Django 5.2 on 2026-01-19 09:22

import payroll.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='maximum_amount',
            field=models.FloatField(blank=True, help_text='The maximum amount for the allowance', null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='maximum_unit',
            field=models.CharField(choices=[('month_working_days', 'For working days on month')], default='month_working_days', help_text='The maximum amount for ?', max_length=20, null=True, verbose_name='Maximum Unit'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_amount',
            field=models.FloatField(blank=True, help_text='The maximum amount for the deduction', null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_unit',
            field=models.CharField(choices=[('month_working_days', 'For working days on month')], default='month_working_days', help_text='The maximum amount for ?', max_length=20, null=True, verbose_name='Maximum Unit'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='installment_start_date',
            field=models.DateField(help_text='From the start date deduction will apply', verbose_name='Installment start date'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='settled',
            field=models.BooleanField(default=False, verbose_name='Settled'),
        ),
        migrations.AlterField(
            model_name='payslipautogenerate',
            name='auto_generate',
            field=models.BooleanField(default=False, verbose_name='Auto Generate'),
        ),
    ]
