# Generated by Django 5.2 on 2026-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_allowance_maximum_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='position',
            field=models.CharField(choices=[('prefix', 'Prefix'), ('postfix', 'Suffix')], default='postfix', max_length=15, null=True),
        ),
    ]
