# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollsettings_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='include_active_employees',
            field=models.BooleanField(default=False, help_text='Target allowance to all active employees in the company', verbose_name='Include All Employees'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='include_active_employees',
            field=models.BooleanField(default=False, help_text='Target deduction to all active employees in the company', verbose_name='Include All Employees'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='type',
            field=models.CharField(choices=[('loan', 'Loan'), ('advanced_salary', 'Salary Advance'), ('fine', 'Penalty / Fine')], default='loan', max_length=15),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_record_type',
            field=models.CharField(choices=[('FDP', 'Present'), ('HDP', 'Half Day Present'), ('ABS', 'Absent'), ('HD', 'Holiday / Weekly Off'), ('CONF', 'Conflict'), ('DFT', 'Draft')], max_length=5, null=True),
        ),
    ]
