# Generated by Django 5.2 on 2026-08-08 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
        ('payroll', '0005_alter_allowance_based_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee_id', 'start_date', 'end_date'), name='unique_payslip_per_employee_period'),
        ),
    ]
