# Generated by Django 5.2 on 2026-08-14 08:25

import django.db.models.deletion
import payroll.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_announcementexpire_company_id_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
        ('payroll', '0006_payslip_unique_payslip_per_employee_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount_per_one_hr',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='based_on',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic Pay'), ('children', 'Children'), ('overtime', 'Regular Overtime'), ('week_off_overtime', 'Week Off Overtime'), ('holiday_overtime', 'Holiday Overtime'), ('shift_id', 'Shift'), ('work_type_id', 'Work Type'), ('attendance', 'Attendance')], default='basic_pay', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='end_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='exclude_employees',
            field=models.ManyToManyField(blank=True, related_name='allowance_excluded', to='employee.employee', verbose_name='Exclude Employees'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='field',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('marital_status', 'Marital Status'), ('experience', 'Experience'), ('employee_work_info__experience', 'Company Experience'), ('gender', 'Gender'), ('country', 'Country'), ('state', 'State'), ('contract_set__pay_frequency', 'Pay Frequency'), ('contract_set__wage_type', 'Wage Type'), ('contract_set__department__department', 'Department on Contract')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='has_max_limit',
            field=models.BooleanField(default=False, verbose_name='Has max limit for allowance'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='if_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='if_choice',
            field=models.CharField(choices=[('basic_pay', 'Basic Pay')], default='basic_pay', max_length=10),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='if_condition',
            field=models.CharField(choices=[('equal', 'Equal (==)'), ('notequal', 'Not Equal (!=)'), ('lt', 'Less Than (<)'), ('gt', 'Greater Than (>)'), ('le', 'Less Than or Equal To (<=)'), ('ge', 'Greater Than or Equal To (>=)'), ('range', 'Range')], default='gt', max_length=10),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='include_active_employees',
            field=models.BooleanField(default=False, verbose_name='Include All Employees'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='is_condition_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='maximum_amount',
            field=models.FloatField(blank=True, null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='maximum_unit',
            field=models.CharField(choices=[('month_working_days', 'For working days on month')], default='month_working_days', max_length=20, null=True, verbose_name='Maximum Unit'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='one_time_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='per_attendance_fixed_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='per_children_fixed_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='rate',
            field=models.FloatField(blank=True, null=True, validators=[payroll.models.models.rate_validator]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='shift_per_attendance_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, related_name='allowance_specific', to='employee.employee', verbose_name='Employees Specific'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='start_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='work_type_per_attendance_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[payroll.models.models.min_zero]),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='based_on',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic Pay'), ('gross_pay', 'Gross Pay'), ('taxable_gross_pay', 'Taxable Gross Pay'), ('net_pay', 'Net Pay')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employer_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.rate_validator]),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='end_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='exclude_employees',
            field=models.ManyToManyField(blank=True, related_name='deduction_exclude', to='employee.employee', verbose_name='Exclude Employees'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='field',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('marital_status', 'Marital Status'), ('experience', 'Experience'), ('employee_work_info__experience', 'Company Experience'), ('gender', 'Gender'), ('country', 'Country'), ('state', 'State'), ('contract_set__pay_frequency', 'Pay Frequency'), ('contract_set__wage_type', 'Wage Type'), ('contract_set__department__department', 'Department on Contract')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='has_max_limit',
            field=models.BooleanField(default=False, verbose_name='Has max limit for deduction'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='if_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='if_choice',
            field=models.CharField(choices=[('basic_pay', 'Basic Pay'), ('gross_pay', 'Gross Pay')], default='basic_pay', max_length=10),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='if_condition',
            field=models.CharField(choices=[('equal', 'Equal (==)'), ('notequal', 'Not Equal (!=)'), ('lt', 'Less Than (<)'), ('gt', 'Greater Than (>)'), ('le', 'Less Than or Equal To (<=)'), ('ge', 'Greater Than or Equal To (>=)'), ('range', 'Range')], default='gt', max_length=10),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='include_active_employees',
            field=models.BooleanField(default=False, verbose_name='Include All Employees'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_condition_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_pretax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_amount',
            field=models.FloatField(blank=True, null=True, validators=[payroll.models.models.min_zero], verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_unit',
            field=models.CharField(choices=[('month_working_days', 'For working days on month')], default='month_working_days', max_length=20, null=True, verbose_name='Maximum Unit'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='one_time_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[payroll.models.models.rate_validator], verbose_name='Employee rate'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, related_name='deduction_specific', to='employee.employee', verbose_name='Employees Specific'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='start_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='update_compensation',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic pay'), ('gross_pay', 'Gross Pay'), ('net_pay', 'Net Pay')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=255)),
                ('allowances', models.ManyToManyField(blank=True, related_name='salary_structures', to='payroll.allowance', verbose_name='Allowances')),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deductions', models.ManyToManyField(blank=True, related_name='salary_structures', to='payroll.deduction', verbose_name='Deductions')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'unique_together': {('title', 'company_id')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_structure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='payroll.salarystructure', verbose_name='Salary Structure'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='salary_structure_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.salarystructure', verbose_name='Salary Structure'),
        ),
    ]
