# Generated by Django 5.2.17 on 2026-09-02 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
        ('payroll', '0007_alter_allowance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['-end_date'], name='payslip_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status', 'end_date'], name='payslip_status_date_idx'),
        ),
    ]
