"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from os.path import join
from pathlib import Path

import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(
        str,
        "django-insecure-j8op9)1q8$1&0^s&p*_0%d#pr@w9qj@1o=3#@d=a(^@9@zd@%j",
    ),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
)

env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

HYDRA_ENVIRONMENT = env("HYDRA_ENVIRONMENT", default="development").strip().lower()
HYDRA_DISABLE_SCHEDULERS = env.bool("HYDRA_DISABLE_SCHEDULERS", default=False)
HYDRA_ALLOW_WEB_DATABASE_INITIALIZATION = env.bool(
    "HYDRA_ALLOW_WEB_DATABASE_INITIALIZATION",
    default=HYDRA_ENVIRONMENT not in {"staging", "production"},
)
HYDRA_REQUIRE_POSTGRES = env.bool(
    "HYDRA_REQUIRE_POSTGRES",
    default=HYDRA_ENVIRONMENT in {"staging", "production"},
)
HYDRA_DEPLOYMENT_REVISION = env("HYDRA_DEPLOYMENT_REVISION", default="").strip()

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "notifications",
    "mathfilters",
    "corsheaders",
    "simple_history",
    "django_filters",
    "base",
    "employee",
    "recruitment",
    "leave",
    "pms",
    "onboarding",
    "asset",
    "attendance",
    "payroll",
    "widget_tweaks",
    "django_apscheduler",
]
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "hydra_ops.middleware.DisableDatabaseInitializationMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "horilla_api.middleware.RejectBasicAuthMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "horilla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if env("DATABASE_URL", default=None):
    DATABASES = {
        "default": env.db(),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(
                    BASE_DIR,
                    "TestDB_Horilla.sqlite3",
                ),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }

DATABASES["default"]["CONN_MAX_AGE"] = env.int(
    "DB_CONN_MAX_AGE",
    default=60 if HYDRA_ENVIRONMENT in {"staging", "production"} else 0,
)
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(env("STATIC_ROOT", default=str(BASE_DIR / "staticfiles")))

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = env("MEDIA_ROOT", default=str(BASE_DIR / "media"))
HYDRA_PRIVATE_MEDIA_ROOT = env(
    "HYDRA_PRIVATE_MEDIA_ROOT",
    default=str(BASE_DIR / ".private_media"),
)
HYDRA_PORTAL_EMAIL_MEDIA_ROOT = env(
    "HYDRA_PORTAL_EMAIL_MEDIA_ROOT",
    default=str(BASE_DIR / ".portal_email_outbox"),
)
HYDRA_PRIVATE_DOCUMENT_MAX_BYTES = env.int(
    "HYDRA_PRIVATE_DOCUMENT_MAX_BYTES",
    default=10 * 1024 * 1024,
)
HYDRA_DOCUMENT_QUARANTINE_ROOT = env(
    "HYDRA_DOCUMENT_QUARANTINE_ROOT",
    default=str(BASE_DIR / ".document_quarantine"),
)
HYDRA_DOCUMENT_QUARANTINE_HOURS = env.int(
    "HYDRA_DOCUMENT_QUARANTINE_HOURS",
    default=72,
)
HYDRA_PRIVATE_DOCUMENT_RETENTION_DAYS = env.int(
    "HYDRA_PRIVATE_DOCUMENT_RETENTION_DAYS",
    default=365,
)
HYDRA_IMPORT_PREVIEW_RETENTION_HOURS = env.int(
    "HYDRA_IMPORT_PREVIEW_RETENTION_HOURS",
    default=72,
)
HYDRA_IMPORT_APPLIED_RETENTION_HOURS = env.int(
    "HYDRA_IMPORT_APPLIED_RETENTION_HOURS",
    default=24,
)
HYDRA_DOCUMENT_SCANNER = env("HYDRA_DOCUMENT_SCANNER", default="disabled")
HYDRA_CLAMD_HOST = env("HYDRA_CLAMD_HOST", default="127.0.0.1")
HYDRA_CLAMD_PORT = env.int("HYDRA_CLAMD_PORT", default=3310)
HYDRA_CLAMD_TIMEOUT_SECONDS = env.int("HYDRA_CLAMD_TIMEOUT_SECONDS", default=30)
HYDRA_NOTIFICATION_MAX_ATTEMPTS = env.int(
    "HYDRA_NOTIFICATION_MAX_ATTEMPTS", default=10
)
HYDRA_NOTIFICATION_BASE_URL = env(
    "HYDRA_NOTIFICATION_BASE_URL",
    default="http://127.0.0.1:8000/",
)
HYDRA_NOTIFICATION_EMAIL_RETRY_BASE_SECONDS = env.int(
    "HYDRA_NOTIFICATION_EMAIL_RETRY_BASE_SECONDS", default=60
)
HYDRA_NOTIFICATION_EMAIL_RETRY_MAX_SECONDS = env.int(
    "HYDRA_NOTIFICATION_EMAIL_RETRY_MAX_SECONDS", default=3600
)
HYDRA_NOTIFICATION_EMAIL_LEASE_SECONDS = env.int(
    "HYDRA_NOTIFICATION_EMAIL_LEASE_SECONDS", default=120
)
HYDRA_ONBOARDING_PORTAL_BASE_URL = env(
    "HYDRA_ONBOARDING_PORTAL_BASE_URL",
    default="http://127.0.0.1:8000/",
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_FAIL_SILENTLY = env.bool("EMAIL_FAIL_SILENTLY", default=False)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=30)
HYDRA_PORTAL_EMAIL_MAX_ATTEMPTS = env.int(
    "HYDRA_PORTAL_EMAIL_MAX_ATTEMPTS", default=8
)
HYDRA_PORTAL_EMAIL_RETRY_BASE_SECONDS = env.int(
    "HYDRA_PORTAL_EMAIL_RETRY_BASE_SECONDS", default=60
)
HYDRA_PORTAL_EMAIL_RETRY_MAX_SECONDS = env.int(
    "HYDRA_PORTAL_EMAIL_RETRY_MAX_SECONDS", default=3600
)
HYDRA_PORTAL_EMAIL_LEASE_SECONDS = env.int(
    "HYDRA_PORTAL_EMAIL_LEASE_SECONDS", default=120
)
HYDRA_PORTAL_EMAIL_DEAD_RETENTION_HOURS = env.int(
    "HYDRA_PORTAL_EMAIL_DEAD_RETENTION_HOURS", default=72
)
HYDRA_PORTAL_EMAIL_MAX_ATTACHMENTS = env.int(
    "HYDRA_PORTAL_EMAIL_MAX_ATTACHMENTS", default=8
)
HYDRA_PORTAL_EMAIL_ATTACHMENT_MAX_BYTES = env.int(
    "HYDRA_PORTAL_EMAIL_ATTACHMENT_MAX_BYTES", default=10 * 1024 * 1024
)
HYDRA_PORTAL_EMAIL_ATTACHMENTS_TOTAL_BYTES = env.int(
    "HYDRA_PORTAL_EMAIL_ATTACHMENTS_TOTAL_BYTES", default=25 * 1024 * 1024
)
HYDRA_MAINTENANCE_INTERVAL_SECONDS = env.int(
    "HYDRA_MAINTENANCE_INTERVAL_SECONDS", default=30
)
HYDRA_MAINTENANCE_STALE_SECONDS = env.int(
    "HYDRA_MAINTENANCE_STALE_SECONDS", default=120
)
HYDRA_MAINTENANCE_PURGE_INTERVAL_SECONDS = env.int(
    "HYDRA_MAINTENANCE_PURGE_INTERVAL_SECONDS", default=3600
)
HYDRA_MAINTENANCE_NOTIFICATION_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_NOTIFICATION_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_NOTIFICATION_EMAIL_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_NOTIFICATION_EMAIL_BATCH_SIZE", default=25
)
HYDRA_MAINTENANCE_DOCUMENT_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_DOCUMENT_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_IMPORT_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_IMPORT_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_LEGALIZATION_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_LEGALIZATION_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_ARRIVAL_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_ARRIVAL_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_HOUSING_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_HOUSING_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_ONBOARDING_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_ONBOARDING_BATCH_SIZE", default=100
)
HYDRA_MAINTENANCE_PORTAL_EMAIL_BATCH_SIZE = env.int(
    "HYDRA_MAINTENANCE_PORTAL_EMAIL_BATCH_SIZE", default=25
)
HYDRA_MAINTENANCE_MAX_FAILURES = env.int(
    "HYDRA_MAINTENANCE_MAX_FAILURES", default=5
)
HYDRA_LEGALIZATION_DEADLINE_REMINDER_DAYS = tuple(
    env.list(
        "HYDRA_LEGALIZATION_DEADLINE_REMINDER_DAYS",
        cast=int,
        default=[30, 7, 1],
    )
)
HYDRA_LEGALIZATION_VALIDITY_REMINDER_DAYS = tuple(
    env.list(
        "HYDRA_LEGALIZATION_VALIDITY_REMINDER_DAYS",
        cast=int,
        default=[90, 30, 7],
    )
)
HYDRA_ARRIVAL_REMINDER_MINUTES = tuple(
    env.list(
        "HYDRA_ARRIVAL_REMINDER_MINUTES",
        cast=int,
        default=[1440, 120],
    )
)
HYDRA_BACKUP_ROOT = env("HYDRA_BACKUP_ROOT", default=str(BASE_DIR / "backups"))
HYDRA_READINESS_REQUIRE_STATIC = env.bool(
    "HYDRA_READINESS_REQUIRE_STATIC",
    default=HYDRA_ENVIRONMENT in {"staging", "production"},
)
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "oh-alert--warning",
    messages.INFO: "oh-alert--info",
    messages.SUCCESS: "oh-alert--success",
    messages.WARNING: "oh-alert--warning",
    messages.ERROR: "oh-alert--danger",
}


CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

LOGIN_URL = "/login"

HYDRA_PORTAL_URL = env(
    "HYDRA_PORTAL_URL",
    default="https://oleksandrkiris.github.io/citronex-hydra-project/",
)


SIMPLE_HISTORY_REVERT_DISABLED = True


DJANGO_NOTIFICATIONS_CONFIG = {
    "USE_JSONFIELD": True,
    "SOFT_DELETE": True,
    "USE_WATCHED": True,
    "NOTIFICATIONS_STORAGE": "notifications.storage.DatabaseStorage",
    "TEMPLATE": "notifications.html",  # Add this line
}

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGES = (
    ("en", "English (US)"),
    ("de", "Deutsche"),
    ("es", "Español"),
    ("fr", "Français"),
    ("ar", "عربى"),
    ("pt-br", "Português (Brasil)"),
    ("zh-hans", "Simplified Chinese"),
    ("zh-hant", "Traditional Chinese"),
    ("it", "Italian"),
    ("uk", "Українська"),
)


LOCALE_PATHS = [
    join(BASE_DIR, "horilla", "locale"),
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="Asia/Kolkata")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Production settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
    )
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health/"]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
FILE_UPLOAD_PERMISSIONS = 0o600
