# Generated by Django 6.0 on 2025-12-09 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-id"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-id"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
