# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'verbose_name': 'Timesheet', 'verbose_name_plural': 'Timesheets'},
        ),
    ]
