# Generated by Django 5.2 on 2026-08-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_timesheet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
