# Generated by Django 5.2.17 on 2026-09-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_project_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheet",
            options={
                "ordering": ("-id",),
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
            },
        ),
    ]
