# Generated by Django 5.2.17 on 2026-09-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_timesheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'verbose_name': 'Timesheet', 'verbose_name_plural': 'Timesheets'},
        ),
    ]
