"""Create demo ResignationLetter rows matching the backfilled exit employees.

Only 2 ResignationLetter rows ship in the fixtures, both dated to the same
single day, so the joining-vs-exiting chart's exit series has nothing to
show even once employee_lifecycle backfills contract_end_date. This creates
one resignation letter per employee that module marks as exited, dated
consistently with that employee's own contract_end_date, so both charts tell
the same story.
"""

from __future__ import annotations

import logging
from datetime import date, timedelta

from django.apps import apps
from django.db import transaction

logger = logging.getLogger(__name__)


@transaction.atomic
def backfill_offboarding_letters(
    today: date | None = None, employee_ids: list[int] | None = None
) -> int:
    """One ResignationLetter per employee_id, planned_to_leave_on = that
    employee's EmployeeWorkInformation.contract_end_date when available."""
    if not apps.is_installed("offboarding") or not employee_ids:
        return 0

    today = today or date.today()

    from employee.models import EmployeeWorkInformation
    from offboarding.models import ResignationLetter

    contract_end_by_employee = dict(
        EmployeeWorkInformation._base_manager.filter(
            employee_id__in=employee_ids
        ).values_list("employee_id", "contract_end_date")
    )

    created_or_updated = 0
    for i, employee_id in enumerate(employee_ids):
        planned = contract_end_by_employee.get(employee_id) or (
            today - timedelta(days=30 * (i + 1))
        )
        letter, _ = ResignationLetter._base_manager.get_or_create(
            employee_id_id=employee_id,
            defaults={
                "title": "Resignation",
                "description": "Demo resignation, generated by the enterprise seeder.",
                "planned_to_leave_on": planned,
                "status": "approved",
            },
        )
        ResignationLetter._base_manager.filter(pk=letter.pk).update(
            planned_to_leave_on=planned, status="approved"
        )
        created_or_updated += 1

    logger.info(
        "Offboarding backfill: %s resignation letter(s) aligned to exited employees",
        created_or_updated,
    )
    return created_or_updated
