"""Give every demo company its own Offboarding pipeline, not just the largest.

offboarding_data.json's one Offboarding row (and all its OffboardingStage/
OffboardingEmployee/ResignationLetter/ExitReason records) is scoped to a
single company. Offboarding.save() auto-creates the standard 5-stage
pipeline for any new Offboarding row, so switching company context on the
other two companies shows no pipeline at all, not just an empty one.

A small, proportional number of each additional company's own employees are
marked exited here, independently of employee_lifecycle.py's own exit
selection (which is deliberately biased toward the default/largest company
for dashboard reasons and shouldn't be disturbed) -- so this never competes
with that module for the same employees.
"""

from __future__ import annotations

import logging
from datetime import date, timedelta

from django.apps import apps
from django.db import transaction

logger = logging.getLogger(__name__)

# Roughly matches employee_lifecycle.py's own ~4% exit rate, applied to
# each additional company's own (much smaller) headcount.
NEW_COMPANY_EXIT_COUNT = {2: 2, 3: 2}

EXIT_REASONS = ("Relocation", "Career change", "Further studies", "Personal reasons")


@transaction.atomic
def backfill_company_offboarding_pipelines(today: date | None = None) -> int:
    """Ensure each company in NEW_COMPANY_EXIT_COUNT has its own Offboarding
    pipeline and a handful of exited employees to populate it."""
    if not apps.is_installed("offboarding"):
        return 0

    today = today or date.today()

    from base.demo_data.modules.employee_lifecycle import _PROTECTED_EMAILS
    from employee.models import Employee, EmployeeWorkInformation
    from offboarding.models import (
        ExitReason,
        Offboarding,
        OffboardingEmployee,
        OffboardingStage,
        ResignationLetter,
    )

    # Excludes rows this same function created on a PRIOR run too -- used only
    # to keep this company's picks disjoint from other seeder modules' exits,
    # never to decide whether to add more (that's bounded against this
    # company's own archived-stage headcount below instead, so repeated
    # non-flush reloads can't keep manufacturing new exits indefinitely).
    already_offboarding_ids = set(
        OffboardingEmployee._base_manager.values_list("employee_id_id", flat=True)
    ) | set(ResignationLetter._base_manager.values_list("employee_id_id", flat=True))

    created = 0
    for company_id, exit_count in NEW_COMPANY_EXIT_COUNT.items():
        offboarding, _ = Offboarding._base_manager.get_or_create(
            company_id_id=company_id,
            defaults={
                "title": "Offboarding",
                "description": "Demo offboarding pipeline.",
            },
        )
        archived_stage = OffboardingStage._base_manager.filter(
            offboarding_id=offboarding, type="archived"
        ).first()
        if not archived_stage:
            continue

        # Employees this function already exited for this company on a prior
        # run -- refresh these instead of always picking `exit_count` new
        # people every reload.
        existing_ids = list(
            OffboardingEmployee._base_manager.filter(stage_id=archived_stage)
            .order_by("employee_id_id")
            .values_list("employee_id_id", flat=True)
        )
        needed = max(0, exit_count - len(existing_ids))
        new_ids = list(
            Employee._base_manager.filter(is_active=True)
            .exclude(email__in=_PROTECTED_EMAILS)
            .exclude(employee_user_id__is_superuser=True)
            .exclude(pk__in=already_offboarding_ids)
            .filter(employee_work_info__company_id=company_id)
            .order_by("id")
            .values_list("id", flat=True)[:needed]
        )
        for employee_id in new_ids:
            Employee._base_manager.filter(pk=employee_id).update(is_active=False)

        employee_ids = existing_ids + new_ids

        for i, employee_id in enumerate(employee_ids):
            planned = today - timedelta(days=30 * (i + 1))
            EmployeeWorkInformation._base_manager.filter(
                employee_id=employee_id
            ).update(contract_end_date=planned)

            letter, _ = ResignationLetter._base_manager.get_or_create(
                employee_id_id=employee_id,
                defaults={
                    "title": "Resignation",
                    "description": "Demo resignation, generated by the enterprise seeder.",
                    "planned_to_leave_on": planned,
                    "status": "approved",
                },
            )
            ResignationLetter._base_manager.filter(pk=letter.pk).update(
                planned_to_leave_on=planned, status="approved"
            )
            offboarding_employee, _ = OffboardingEmployee._base_manager.get_or_create(
                employee_id_id=employee_id,
                defaults={
                    "stage_id": archived_stage,
                    "notice_period_starts": planned,
                    "notice_period_ends": planned,
                },
            )
            OffboardingEmployee._base_manager.filter(pk=offboarding_employee.pk).update(
                notice_period_starts=planned, notice_period_ends=planned
            )
            ExitReason._base_manager.get_or_create(
                offboarding_employee_id=offboarding_employee,
                defaults={
                    "title": EXIT_REASONS[i % len(EXIT_REASONS)],
                    "description": "Demo exit reason, generated by the enterprise seeder.",
                },
            )
            created += 1

    logger.info(
        "Offboarding backfill: created %s exited employee(s) across %s new company pipeline(s)",
        created,
        len(NEW_COMPANY_EXIT_COUNT),
    )
    return created
