# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktyperequest',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_type_request', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='worktyperequest',
            name='previous_work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_work_type', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='worktyperequest',
            name='work_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_work_type', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_request', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='previous_shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_shift', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_shift', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='rotatingworktypeassign',
            name='current_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_work_type', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='rotatingworktypeassign',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='rotatingworktypeassign',
            name='next_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_work_type', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='rotatingworktypeassign',
            name='rotating_work_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rotatingworktype'),
        ),
        migrations.AddField(
            model_name='rotatingworktype',
            name='employee_id',
            field=models.ManyToManyField(through='base.RotatingWorkTypeAssign', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='rotatingworktype',
            name='work_type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type1', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='rotatingworktype',
            name='work_type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type2', to='base.worktype'),
        ),
        migrations.AddField(
            model_name='rotatingshiftassign',
            name='current_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_shift', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='rotatingshiftassign',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='rotatingshiftassign',
            name='next_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_shift', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='rotatingshiftassign',
            name='rotating_shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rotatingshift'),
        ),
        migrations.AddField(
            model_name='rotatingshift',
            name='employee_id',
            field=models.ManyToManyField(through='base.RotatingShiftAssign', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='rotatingshift',
            name='shift1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift1', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='rotatingshift',
            name='shift2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift2', to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='job_position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposition'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='department_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='base.department'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedule', to='base.employeeshiftday'),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='days',
            field=models.ManyToManyField(through='base.EmployeeShiftSchedule', to='base.employeeshiftday'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='worktyperequest',
            unique_together={('employee_id', 'requested_date')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftrequest',
            unique_together={('employee_id', 'requested_date')},
        ),
        migrations.AlterUniqueTogether(
            name='jobrole',
            unique_together={('job_position_id', 'job_role')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeshiftschedule',
            unique_together={('shift_id', 'day')},
        ),
    ]
