# Generated by Django 5.2 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='company_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='use_dynamic_display_name',
            field=models.BooleanField(default=True, help_text='By enabling this the display name will take from who triggered the mail', verbose_name='Use dynamic display name'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='employee_shift',
            field=models.CharField(max_length=50, verbose_name='Employee Shift'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='employee_type',
            field=models.CharField(max_length=50, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='condition_field',
            field=models.CharField(choices=[('', '---------'), ('requested_days', 'Leave Requested Days')], max_length=255, verbose_name='Condition Field'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('equal', 'Equal (==)'), ('notequal', 'Not Equal (!=)'), ('range', 'Range'), ('lt', 'Less Than (<)'), ('gt', 'Greater Than (>)'), ('le', 'Less Than or Equal To (<=)'), ('ge', 'Greater Than or Equal To (>=)'), ('icontains', 'Contains')], max_length=255, null=True, verbose_name='Condition Operator'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='deduct_from_carry_forward',
            field=models.BooleanField(default=False, verbose_name='Deduct from Carry Forward'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='minus_leaves',
            field=models.FloatField(default=0.0, null=True, verbose_name='Minus Leaves'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='penalty_amount',
            field=models.FloatField(default=0.0, null=True, verbose_name='Penalty Amount'),
        ),
    ]
