# Generated by Django 5.2 on 2026-06-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dynamicemailconfiguration_company_id_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('published_on', models.DateTimeField(auto_now_add=True, verbose_name='Published On')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Total Employees')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_publish_logs', to='base.department', verbose_name='Department')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_publishes', to='employee.employee', verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'Roster Publish Log',
                'verbose_name_plural': 'Roster Publish Logs',
                'ordering': ['-published_on'],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_published', models.BooleanField(default=False, help_text='Visible to the employee once published.', verbose_name='Published')),
                ('is_off', models.BooleanField(default=False, help_text='Planned weekly rest day.', verbose_name='Day Off')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_entries', to='employee.employee', verbose_name='Created By')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='base.department', verbose_name='Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to='base.employeeshift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Roster Entry',
                'verbose_name_plural': 'Roster Entries',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
