# Generated by Django 5.2 on 2026-06-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rosterpublishlog_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklatecomeearlyout',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company'),
        ),
    ]
