# Generated by Django 5.2 on 2026-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendanceallowedip_company_id_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='assigning_type',
            field=models.CharField(blank=True, choices=[('department', 'Department'), ('job_position', 'Job Position'), ('employee', 'Employee')], max_length=100, null=True, verbose_name='Assigning Type'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='holiday_departments', to='base.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='is_specific',
            field=models.BooleanField(default=False, verbose_name='Is Specific'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='job_position',
            field=models.ManyToManyField(blank=True, related_name='holiday_job_positions', to='base.jobposition', verbose_name='Job Position'),
        ),
    ]
