# Generated by Django 5.2 on 2026-07-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_holidays_assigning_type_holidays_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupChecklistDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_checklist_dismissals', to='base.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_checklist_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setup Checklist Dismissal',
                'verbose_name_plural': 'Setup Checklist Dismissals',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
