# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_companylanguagesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyleaves',
            options={'verbose_name': 'Weekly Off Day', 'verbose_name_plural': 'Weekly Off Days'},
        ),
        migrations.AlterModelOptions(
            name='tracklatecomeearlyout',
            options={'verbose_name': 'Track Late Arrival & Early Departure', 'verbose_name_plural': 'Track Late Arrival & Early Departure'},
        ),
    ]
