# Generated by Django 5.2 on 2026-08-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_companyleaves_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyleaves',
            name='company_id',
        ),
        migrations.AddField(
            model_name='companyleaves',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='base.company', verbose_name='Company'),
        ),
    ]
