# Generated by Django 5.2 on 2026-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_announcementexpire_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotatingworktype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
