# Generated by Django 5.2.17 on 2026-09-05 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rotatingworktype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='defaultexportpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('company_id__isnull', False)), fields=('company_id',), name='unique_default_export_permission_per_company'),
        ),
        migrations.AddConstraint(
            model_name='defaultexportpermission',
            constraint=models.UniqueConstraint(models.Q(('company_id__isnull', True)), condition=models.Q(('company_id__isnull', True)), name='unique_default_export_permission_all_companies'),
        ),
    ]
