# Generated by Django 4.2.7 on 2024-02-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10)),
                ('max_size', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.ManyToManyField(to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('document', models.FileField(null=True, upload_to='employee/documents')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notify_before', models.IntegerField(default=1, null=True)),
                ('is_digital_asset', models.BooleanField(default=False)),
                ('document_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horilla_documents.documentrequest')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
