# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Rejection Reason'),
        ),
    ]
