# Generated by Django 5.2.7 on 2025-10-29 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappCredientials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("meta_token", models.TextField()),
                ("meta_business_id", models.CharField(max_length=255)),
                ("meta_phone_number_id", models.CharField(max_length=255)),
                ("meta_phone_number", models.CharField(max_length=20)),
                ("created_templates", models.BooleanField(default=False)),
                (
                    "meta_webhook_token",
                    models.CharField(
                        help_text="This token is used to connect webhook to the server",
                        max_length=50,
                        verbose_name="Webhook Token",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "company_id",
                    models.ManyToManyField(
                        blank=True, to="base.company", verbose_name="Company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhatsappFlowDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.CharField(max_length=50)),
                ("flow_id", models.CharField(max_length=50)),
                (
                    "whatsapp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatsapp.whatsappcredientials",
                    ),
                ),
            ],
        ),
    ]
