# Generated by Django 5.2.17 on 2026-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcredientials',
            name='meta_app_secret',
            field=models.CharField(blank=True, default='', help_text='Meta app secret, used to verify the X-Hub-Signature-256 header on incoming webhook calls. Without it Horilla cannot tell a real delivery from a forged one, so unsigned payloads are rejected. Find it under App Settings > Basic in the Meta developer console.', max_length=255, verbose_name='App Secret'),
        ),
    ]
