# Generated by Django 5.2 on 2026-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboardingemployee',
            name='notice_period_ends',
            field=models.DateField(blank=True, null=True, verbose_name='Notice Period Ends'),
        ),
        migrations.AlterField(
            model_name='offboardingemployee',
            name='notice_period_starts',
            field=models.DateField(null=True, verbose_name='Notice Period Starts'),
        ),
        migrations.AlterField(
            model_name='resignationletter',
            name='planned_to_leave_on',
            field=models.DateField(verbose_name='Planned To Leave On'),
        ),
    ]
