# Generated by Django 5.2 on 2026-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0002_alter_offboardingemployee_notice_period_ends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingtask',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
    ]
