# Generated by Django 5.2.7 on 2025-10-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoFencing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_in_meters", models.IntegerField()),
                ("start", models.BooleanField(default=False)),
                (
                    "company_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_fencing",
                        to="base.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("company_id", None), _negated=True),
                        fields=("company_id",),
                        name="unique_company_id_when_not_null_geofencing",
                    )
                ],
            },
        ),
    ]
