# Generated by Django 5.2.8 on 2025-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LDAPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ldap_server",
                    models.CharField(default="ldap://127.0.0.1:389", max_length=255),
                ),
                (
                    "bind_dn",
                    models.CharField(
                        default="cn=admin,dc=horilla,dc=com", max_length=255
                    ),
                ),
                ("bind_password", models.CharField(max_length=255)),
                (
                    "base_dn",
                    models.CharField(
                        default="ou=users,dc=horilla,dc=com", max_length=255
                    ),
                ),
            ],
        ),
    ]
