# Generated by Django 5.2 on 2026-07-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_ldap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapsettings',
            options={'verbose_name': 'LDAP Settings'},
        ),
    ]
