from django.utils.translation import gettext as _

_("monday"),
_("tuesday"),
_("wednesday"),
_("thursday"),
_("friday"),
_("saturday"),
_("sunday"),
_("after"),
_("weekly"),
_("monthly"),
_("Employee First Name"),
_("Employee Last Name"),
_("Bank Code #1"),
_("Bank Code #2"),
_("RECRUITMENT"),
_("ONBOARDING"),
_("EMPLOYEE"),
_("PAYROLL"),
_("ATTENDANCE"),
_("LEAVE"),
_("ASSET"),
_("Your asset request approved!."),
_("Your asset request rejected!."),
_("You are added to rotating work type"),
_("You are added to rotating shift"),
_("Your work type request has been canceled."),
_("Your work type request has been approved."),
_("Your work type request has been deleted."),
_("Your shift request has been canceled."),
_("Your shift request has been approved."),
_("Your shift request has been deleted."),
_("Your work details has been updated."),
_("You have a new leave request to validate."),
_("New leave type is assigned to you"),
_("Your Leave request has been cancelled"),
_("Your Leave request has been approved"),
_("You are chosen as onboarding stage manager"),
_("You are chosen as onboarding task manager"),
_("You got an OKR!."),
_("You have received feedback!"),
_("You have been assigned as a manager in a feedback!"),
_("You have been assigned as a subordinate in a feedback!"),
_("You have been assigned as a colleague in a feedback!"),
_("You are chosen as one of recruitment manager"),
_("Your attendance for the date "),
_(" is validated"),
_("Select"),
_("January"),
_("February"),
_("March"),
_("April"),
_("May"),
_("June"),
_("July"),
_("August"),
_("September"),
_("October"),
_("November"),
_("December"),
_("One time date"),
_("Is condition based"),
_("Is taxable"),
_("Is fixed"),
_("Value"),
_("If choice"),
_("Is tax"),
_("If amount"),
_("If condition"),
_("Employer rate"),
_("Contract name"),
_("Contract start date"),
_("Contract end date"),
_("Wage type"),
_("Calculate daily leave amount"),
_("Deduction for one leave amount"),
_("Deduct leave from basic pay"),
_("Job role"),
_("Work type"),
_("Pay frequency"),
_("Filing status"),
_("Contract status"),
_("Contract document"),
_("Is tax"),
_("Update compensation"),
_("Is pretax"),
_("DASHBOARD"),
_("SHIFT REQUESTS"),
_("WORK TYPE REQUESTS"),
_("ATTENDANCE"),
_("ASSET"),
_("Single"),
_("Married"),
_("Divorced"),
_("Description"),
_("Rotate every weekend"),
_("Rotate every"),
_("Request description"),
_("Attendance validated"),
_("Is validate request"),
_("Is validate request approved"),
_("Reporting Manager"),
_("Employment Type"),
_("Jan"),
_("Feb"),
_("Mar"),
_("Apr"),
_("May"),
_("Jun"),
_("Jul"),
_("Aug"),
_("Sep"),
_("Oct"),
_("Nov"),
_("Dec"),
_("Additional info"),
