# Generated by Django 4.2.24 on 2026-07-15 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceState',
            fields=[
                ('key', models.CharField(default='primary', editable=False, max_length=40, primary_key=True, serialize=False)),
                ('owner_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('started_at', models.DateTimeField()),
                ('heartbeat_at', models.DateTimeField(db_index=True)),
                ('last_cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_cycle_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('last_document_purge_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'permissions': (('view_maintenancestate', 'Can view Hydra maintenance state'),),
                'default_permissions': (),
            },
        ),
    ]
