# Generated by Django 4.2.24 on 2026-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_ops', '0002_maintenancestate_last_legalization_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='last_arrival_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
