# Generated by Django 4.2.24 on 2026-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_ops', '0003_maintenancestate_last_arrival_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='last_onboarding_reconcile_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
