# Generated by Django 4.2.24 on 2026-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_ops', '0004_maintenancestate_last_onboarding_reconcile_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='last_portal_email_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
