# Generated by Django 4.2.24 on 2026-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_ops', '0005_maintenancestate_last_portal_email_dispatch_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='last_housing_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
