# Generated by Django 4.2.7 on 2024-02-17 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horilla_audit', '0001_initial'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('todo', 'Todo'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('stuck', 'Stuck'), ('done', 'Done')], default='todo', max_length=50, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_task', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Candidate onboarding task',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(null=True)),
                ('is_final_stage', models.BooleanField(default=False)),
                ('employee_id', models.ManyToManyField(to='employee.employee')),
                ('recruitment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_stage', to='recruitment.recruitment', verbose_name='Recruitment')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('candidates', models.ManyToManyField(blank=True, related_name='cand_onboarding_task', to='recruitment.candidate')),
                ('employee_id', models.ManyToManyField(related_name='onboarding_task', to='employee.employee')),
                ('stage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_task', to='onboarding.onboardingstage')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_portal', to='recruitment.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCandidateTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_title', models.CharField(blank=True, max_length=20, null=True)),
                ('history_description', models.TextField(null=True)),
                ('history_highlight', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('todo', 'Todo'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('stuck', 'Stuck'), ('done', 'Done')], default='todo', max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidate_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recruitment.candidate')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_set', to='onboarding.candidatetask')),
                ('history_tags', models.ManyToManyField(to='horilla_audit.audittag')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('onboarding_task_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='onboarding.onboardingtask')),
                ('stage_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='onboarding.onboardingstage')),
            ],
            options={
                'verbose_name': 'historical Candidate onboarding task',
                'verbose_name_plural': 'historical Candidate onboarding tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='candidatetask',
            name='onboarding_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.onboardingtask'),
        ),
        migrations.AddField(
            model_name='candidatetask',
            name='stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_task', to='onboarding.onboardingstage'),
        ),
        migrations.CreateModel(
            name='CandidateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_end_date', models.DateField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0, null=True)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_stage', to='recruitment.candidate')),
                ('onboarding_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate', to='onboarding.onboardingstage')),
            ],
            options={
                'verbose_name': 'Candidate Onboarding stage',
                'ordering': ['sequence'],
            },
        ),
    ]
