# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('employee_id', models.ManyToManyField(to='employee.employee')),
                ('recruitment_id', models.ManyToManyField(related_name='onboarding_task', to='recruitment.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(null=True)),
                ('employee_id', models.ManyToManyField(to='employee.employee')),
                ('recruitment_id', models.ManyToManyField(to='recruitment.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_portal', to='recruitment.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_stage', to='recruitment.candidate')),
                ('onboarding_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='onboarding.onboardingstage')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('ongoing', 'Ongoing'), ('stuck', 'Stuck'), ('done', 'Done')], max_length=50, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_task', to='recruitment.candidate')),
                ('onboarding_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask')),
            ],
            options={
                'unique_together': {('candidate_id', 'onboarding_task_id')},
            },
        ),
    ]
