# Generated by Django 5.2 on 2026-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Required tasks must be completed by the candidate to move to the next stage.', verbose_name='Is Required'),
        ),
    ]
