# Generated by Django 4.2.24 on 2026-07-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hydra_coordination", "0001_initial"),
        ("hydra_people", "0002_personapplication_link_source"),
        ("recruitment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrivalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("planned_at", models.DateTimeField()),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("air", "Air"),
                            ("train", "Train"),
                            ("car", "Car"),
                            ("other", "Other"),
                        ],
                        default="bus",
                        max_length=16,
                    ),
                ),
                ("transport_reference", models.CharField(blank=True, max_length=100)),
                ("pickup_point", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("no_show", "No-show"),
                        ],
                        default="planned",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "actual_arrived_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "no_show_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_arrival_plans",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_arrival_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrival_plans",
                        to="hydra_coordination.location",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrival_plans",
                        to="hydra_people.person",
                    ),
                ),
            ],
            options={
                "ordering": ("planned_at", "person__passport_name", "pk"),
                "permissions": (
                    ("assign_arrivalplan", "Can assign arrival coordinators"),
                    (
                        "transition_arrivalplan",
                        "Can confirm or mark no-show arrivals",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="ArrivalStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("no_show", "No-show"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("no_show", "No-show"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrival_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="hydra_arrivals.arrivalplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "default_permissions": (),
                "permissions": (
                    (
                        "view_arrivalstatushistory",
                        "Can view arrival status history",
                    ),
                ),
            },
        ),
        migrations.AddConstraint(
            model_name="arrivalplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "planned")),
                fields=("candidate",),
                name="hyd_arr_active_candidate_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="arrivalplan",
            index=models.Index(
                fields=["destination_location", "status", "planned_at"],
                name="hyd_arr_location_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrivalplan",
            index=models.Index(
                fields=["coordinator", "status", "planned_at"],
                name="hyd_arr_coord_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrivalplan",
            index=models.Index(
                fields=["person", "status"],
                name="hyd_arr_person_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrivalstatushistory",
            index=models.Index(
                fields=["plan", "occurred_at"],
                name="hyd_arr_history_idx",
            ),
        ),
    ]
