# Generated by Django 4.2.24 on 2026-07-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('hydra_arrivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalplan',
            options={'ordering': ('planned_at', 'person__passport_name', 'pk'), 'permissions': (('assign_arrivalplan', 'Can assign arrival coordinators'), ('transition_arrivalplan', 'Can confirm or mark no-show arrivals'), ('receive_arrival_escalations', 'Can receive scoped overdue arrival escalations'))},
        ),
        migrations.CreateModel(
            name='ArrivalAutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('upcoming', 'Upcoming arrival'), ('overdue', 'Overdue arrival')], max_length=16)),
                ('planned_at', models.DateTimeField()),
                ('threshold_minutes', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('notification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notification_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notification_error_code', models.CharField(blank=True, max_length=80)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_arrival_automation_events', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_events', to='hydra_arrivals.arrivalplan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_arrival_automation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('view_arrivalautomationevent', 'Can view arrival automation events'),),
                'default_permissions': (),
                'indexes': [models.Index(fields=['notification_status', 'occurred_at'], name='hyd_arr_auto_notify_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='arrivalautomationevent',
            constraint=models.UniqueConstraint(fields=('plan', 'event_type', 'planned_at', 'threshold_minutes', 'recipient'), name='hyd_arr_auto_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='arrivalautomationevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type', 'upcoming'), ('threshold_minutes__gt', 0)), models.Q(('event_type', 'overdue'), ('threshold_minutes', 0)), _connector='OR'), name='hyd_arr_auto_threshold'),
        ),
        migrations.AddConstraint(
            model_name='arrivalautomationevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('notification_status', 'sent'), _negated=True), ('notification__isnull', False), _connector='OR'), name='hyd_arr_auto_sent_record'),
        ),
    ]
