# Generated by Django 4.2.24 on 2026-07-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0001_initial'),
        ('hydra_coordination', '0004_organizationaccessevent_and_more'),
        ('recruitment', '0001_initial'),
        ('hydra_people', '0003_employee_conversion'),
        ('hydra_arrivals', '0002_alter_arrivalplan_options_arrivalautomationevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('converted', 'Employee converted'), ('completed', 'Completed')], default='started', editable=False, max_length=16)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('started_snapshot', models.JSONField(editable=False)),
                ('arrival', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff', to='hydra_arrivals.arrivalplan')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_onboarding_handoff', to='recruitment.candidate')),
                ('candidate_stage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_handoff', to='onboarding.candidatestage')),
                ('employee_conversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff', to='hydra_people.employeeconversion')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_onboarding_handoffs', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff', to='hydra_people.person')),
                ('person_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff', to='hydra_coordination.personassignment')),
            ],
            options={
                'ordering': ('-initiated_at', '-pk'),
                'permissions': (('initiate_onboardinghandoff', 'Can initiate a confirmed-arrival onboarding handoff'), ('reconcile_onboardinghandoff', 'Can reconcile onboarding handoff milestones')),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingHandoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Handoff started'), ('conversion', 'Employee conversion recorded'), ('assignment', 'Team assignment recorded'), ('completed', 'Handoff completed')], max_length=16)),
                ('source', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=12)),
                ('snapshot', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff_events', to=settings.AUTH_USER_MODEL)),
                ('employee_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff_events', to='hydra_people.employeeconversion')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hydra_arrivals.onboardinghandoff')),
                ('person_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoff_events', to='hydra_coordination.personassignment')),
            ],
            options={
                'ordering': ('occurred_at', 'pk'),
                'permissions': (('view_onboardinghandoffevent', 'Can view onboarding handoff events'),),
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoffevent',
            constraint=models.UniqueConstraint(fields=('handoff', 'event_type'), name='hyd_arr_handoff_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoffevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', False), ('source', 'user')), models.Q(('actor__isnull', True), ('source', 'system')), _connector='OR'), name='hyd_arr_handoff_event_actor'),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoffevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('employee_conversion__isnull', True), ('event_type', 'started'), ('person_assignment__isnull', True)), models.Q(('employee_conversion__isnull', False), ('event_type', 'conversion'), ('person_assignment__isnull', True)), models.Q(('event_type', 'assignment'), ('person_assignment__isnull', False)), models.Q(('employee_conversion__isnull', False), ('event_type', 'completed'), ('person_assignment__isnull', False)), _connector='OR'), name='hyd_arr_handoff_event_shape'),
        ),
        migrations.AddIndex(
            model_name='onboardinghandoff',
            index=models.Index(fields=['status', 'last_reconciled_at'], name='hyd_arr_handoff_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoff',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', True), ('employee_conversion__isnull', True), ('person_assignment__isnull', True), ('status', 'started')), models.Q(('completed_at__isnull', True), ('employee_conversion__isnull', False), ('person_assignment__isnull', True), ('status', 'converted')), models.Q(('completed_at__isnull', False), ('employee_conversion__isnull', False), ('person_assignment__isnull', False), ('status', 'completed')), _connector='OR'), name='hyd_arr_handoff_state_shape'),
        ),
    ]
