# Generated by Django 4.2.24 on 2026-07-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_coordination', '0004_organizationaccessevent_and_more'),
        ('hydra_people', '0003_employee_conversion'),
        ('hydra_arrivals', '0003_onboardinghandoff_onboardinghandoffevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinghandoff',
            name='employee_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoffs', to='hydra_people.employeeconversion'),
        ),
        migrations.AlterField(
            model_name='onboardinghandoff',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoffs', to='hydra_people.person'),
        ),
        migrations.AlterField(
            model_name='onboardinghandoff',
            name='person_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_handoffs', to='hydra_coordination.personassignment'),
        ),
    ]
