# Generated by Django 4.2.24 on 2026-07-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_arrivals', '0004_alter_onboardinghandoff_employee_conversion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onboardinghandoff',
            name='hyd_arr_handoff_state_shape',
        ),
        migrations.AlterField(
            model_name='onboardinghandoff',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('converted', 'Employee converted'), ('assigned', 'Team assigned; tasks pending'), ('completed', 'Completed')], default='started', editable=False, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoff',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', True), ('employee_conversion__isnull', True), ('person_assignment__isnull', True), ('status', 'started')), models.Q(('completed_at__isnull', True), ('employee_conversion__isnull', False), ('person_assignment__isnull', True), ('status', 'converted')), models.Q(('completed_at__isnull', True), ('employee_conversion__isnull', False), ('person_assignment__isnull', False), ('status', 'assigned')), models.Q(('completed_at__isnull', False), ('employee_conversion__isnull', False), ('person_assignment__isnull', False), ('status', 'completed')), _connector='OR'), name='hyd_arr_handoff_state_shape'),
        ),
    ]
