# Generated by Django 4.2.24 on 2026-07-15 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hydra_arrivals.models
import hydra_arrivals.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('base', '0002_initial'),
        ('hydra_arrivals', '0005_remove_onboardinghandoff_hyd_arr_handoff_state_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPortalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('portal_token', models.CharField(editable=False, max_length=200)),
                ('recipient', models.EmailField(editable=False, max_length=254)),
                ('subject', models.CharField(editable=False, max_length=255)),
                ('body_html', models.TextField(editable=False)),
                ('payload_sha256', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('retry', 'Waiting for retry'), ('sent', 'Sent'), ('dead', 'Retries exhausted'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('onboarding_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error_code', models.CharField(blank=True, editable=False, max_length=80)),
                ('onboarding_error_code', models.CharField(blank=True, editable=False, max_length=80)),
                ('payload_purged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_portal_deliveries', to='recruitment.candidate')),
                ('email_configuration', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydra_portal_deliveries', to='base.dynamicemailconfiguration')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydra_deliveries', to='onboarding.onboardingportal')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_onboarding_portal_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', '-pk'),
                'permissions': (('retry_onboardingportaldelivery', 'Can retry portal email delivery'),),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingPortalDeliveryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(blank=True, max_length=255, storage=hydra_arrivals.storage.PortalEmailStorage(base_url=None), upload_to=hydra_arrivals.models.portal_email_attachment_path)),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('content_type', models.CharField(editable=False, max_length=50)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('purged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='hydra_arrivals.onboardingportaldelivery')),
            ],
            options={
                'ordering': ('pk',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OnboardingPortalDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed for delivery'), ('retry', 'Retry scheduled'), ('sent', 'Sent'), ('dead', 'Retries exhausted'), ('cancelled', 'Cancelled'), ('manual_retry', 'Manual retry'), ('onboarding', 'Onboarding started'), ('onboarding_failed', 'Onboarding start failed'), ('purged', 'Payload purged')], max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_portal_delivery_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hydra_arrivals.onboardingportaldelivery')),
            ],
            options={
                'ordering': ('occurred_at', 'pk'),
                'permissions': (('view_onboardingportaldeliveryevent', 'Can view portal delivery events'),),
                'default_permissions': (),
                'indexes': [models.Index(fields=['delivery', 'occurred_at'], name='hyd_arr_portal_event_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingportaldeliveryattachment',
            constraint=models.CheckConstraint(check=models.Q(('size__gt', 0)), name='hyd_arr_portal_att_size_pos'),
        ),
        migrations.AddIndex(
            model_name='onboardingportaldelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='hyd_arr_portal_due_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingportaldelivery',
            index=models.Index(fields=['candidate', 'requested_at'], name='hyd_arr_portal_cand_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingportaldelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'retry', 'sending'))), fields=('candidate',), name='hyd_arr_portal_one_active'),
        ),
        migrations.AddConstraint(
            model_name='onboardingportaldelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lease_expires_at__isnull', True), ('lease_token__isnull', True), ('sent_at__isnull', True), ('status', 'pending')), models.Q(('lease_expires_at__isnull', True), ('lease_token__isnull', True), ('sent_at__isnull', True), ('status', 'retry')), models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('sent_at__isnull', True), ('status', 'sending')), models.Q(('lease_expires_at__isnull', True), ('lease_token__isnull', True), ('sent_at__isnull', False), ('status', 'sent')), models.Q(('lease_expires_at__isnull', True), ('lease_token__isnull', True), ('sent_at__isnull', True), ('status__in', ('dead', 'cancelled'))), _connector='OR'), name='hyd_arr_portal_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='onboardingportaldelivery',
            constraint=models.CheckConstraint(check=models.Q(('attempts__gte', 0)), name='hyd_arr_portal_attempts_nonneg'),
        ),
    ]
