# Generated by Django 4.2.24 on 2026-07-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "format",
                    models.CharField(choices=[("csv", "CSV")], max_length=8),
                ),
                ("filename", models.CharField(max_length=255)),
                ("row_count", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("filters", models.JSONField(default=dict)),
                ("scope_location_ids", models.JSONField(default=list)),
                ("scope_team_ids", models.JSONField(default=list)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydra_operational_report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-pk"),
                "default_permissions": (),
                "permissions": (
                    (
                        "view_operational_report",
                        "Can view the Hydra operational report",
                    ),
                    (
                        "export_operational_report",
                        "Can export the Hydra operational report",
                    ),
                    (
                        "view_operationalreportexport",
                        "Can view operational report export audit",
                    ),
                ),
                "indexes": [
                    models.Index(
                        fields=["actor", "occurred_at"],
                        name="hyd_report_actor_time_idx",
                    )
                ],
            },
        ),
    ]
