# Generated by Django 4.1.4 on 2023-05-11 13:20

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(validators=[attendance.models.attendance_date_validate])),
                ('attendance_clock_in', models.TimeField(null=True)),
                ('attendance_clock_in_date', models.DateField(null=True)),
                ('attendance_clock_out', models.TimeField(null=True)),
                ('attendance_clock_out_date', models.DateField(null=True)),
                ('attendance_worked_hour', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format])),
                ('minimum_hour', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format])),
                ('attendance_overtime', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format])),
                ('attendance_overtime_approve', models.BooleanField(default=False)),
                ('attendance_validated', models.BooleanField(default=False)),
                ('at_work_second', models.IntegerField(blank=True, null=True)),
                ('overtime_second', models.IntegerField(blank=True, null=True)),
                ('approved_overtime_second', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-attendance_date', 'employee_id__employee_first_name', 'attendance_clock_in'],
                'permissions': [('change_validateattendance', 'Validate Attendance'), ('change_approveovertime', 'Change Approve Overtime')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(null=True, validators=[attendance.models.attendance_date_validate])),
                ('clock_in_date', models.DateField(null=True)),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField(null=True)),
                ('clock_out_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-attendance_date', 'employee_id__employee_first_name', 'clock_in'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLateComeEarlyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('late_come', 'Late Come'), ('early_out', 'Early Out')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceOverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('month_sequence', models.PositiveSmallIntegerField(default=0)),
                ('year', models.CharField(default='2023', max_length=10, null=True)),
                ('hour_account', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format])),
                ('overtime', models.CharField(default='00:00', max_length=20, validators=[attendance.models.validate_time_format])),
                ('hour_account_second', models.IntegerField(default=0, null=True)),
                ('overtime_second', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-year', '-month_sequence'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceValidationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_at_work', models.CharField(default='09:00', max_length=10, validators=[attendance.models.validate_time_format])),
                ('minimum_overtime_to_approve', models.CharField(default='00:30', max_length=10, null=True, validators=[attendance.models.validate_time_format])),
                ('overtime_cutoff', models.CharField(default='02:00', max_length=10, null=True, validators=[attendance.models.validate_time_format])),
            ],
        ),
    ]
