# Generated by Django 4.2.7 on 2024-02-17 05:11

import attendance.models
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(validators=[attendance.models.attendance_date_validate], verbose_name='Attendance date')),
                ('attendance_clock_in_date', models.DateField(null=True, verbose_name='Check-In Date')),
                ('attendance_clock_in', models.TimeField(help_text='First Check-In Time', null=True, verbose_name='Check-In')),
                ('attendance_clock_out_date', models.DateField(null=True, verbose_name='Check-Out Date')),
                ('attendance_clock_out', models.TimeField(help_text='Last Check-Out Time', null=True, verbose_name='Check-Out')),
                ('attendance_worked_hour', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format], verbose_name='Worked Hours')),
                ('minimum_hour', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format], verbose_name='Minimum hour')),
                ('attendance_overtime', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format], verbose_name='Overtime')),
                ('attendance_overtime_approve', models.BooleanField(default=False, verbose_name='Overtime approved')),
                ('attendance_validated', models.BooleanField(default=False, verbose_name='Attendance validated')),
                ('at_work_second', models.IntegerField(blank=True, null=True)),
                ('overtime_second', models.IntegerField(blank=True, null=True, verbose_name='Overtime In Second')),
                ('approved_overtime_second', models.IntegerField(default=0)),
                ('is_validate_request', models.BooleanField(default=False, verbose_name='Is validate request')),
                ('is_validate_request_approved', models.BooleanField(default=False, verbose_name='Is validate request approved')),
                ('request_description', models.TextField(null=True)),
                ('request_type', models.CharField(choices=[('create_request', 'Create Request'), ('update_request', 'Update Request'), ('revalidate_request', 'Re-validate Request')], default='update_request', max_length=18, null=True)),
                ('requested_data', models.JSONField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-attendance_date', 'employee_id__employee_first_name', 'attendance_clock_in'],
                'permissions': [('change_validateattendance', 'Validate Attendance'), ('change_approveovertime', 'Change Approve Overtime')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(null=True, validators=[attendance.models.attendance_date_validate], verbose_name='Attendance Date')),
                ('in_datetime', models.DateTimeField(null=True)),
                ('clock_in_date', models.DateField(null=True, verbose_name='In Date')),
                ('clock_in', models.TimeField(verbose_name='Check In')),
                ('clock_out_date', models.DateField(null=True, verbose_name='Out Date')),
                ('out_datetime', models.DateTimeField(null=True)),
                ('clock_out', models.TimeField(null=True, verbose_name='Check Out')),
            ],
            options={
                'ordering': ['-attendance_date', 'employee_id__employee_first_name', 'clock_in'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceGeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_runner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLateComeEarlyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('late_come', 'Late Come'), ('early_out', 'Early Out')], max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-attendance_id__attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceOverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, verbose_name='Month')),
                ('month_sequence', models.PositiveSmallIntegerField(default=0)),
                ('year', models.CharField(default='2024', max_length=10, null=True, verbose_name='Year')),
                ('worked_hours', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format], verbose_name='Worked Hours')),
                ('pending_hours', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format], verbose_name='Pending Hours')),
                ('overtime', models.CharField(default='00:00', max_length=20, validators=[attendance.models.validate_time_format], verbose_name='Overtime Hours')),
                ('hour_account_second', models.IntegerField(default=0, null=True, verbose_name='Worked Seconds')),
                ('hour_pending_second', models.IntegerField(default=0, null=True, verbose_name='Pending Seconds')),
                ('overtime_second', models.IntegerField(default=0, null=True, verbose_name='Overtime Seconds')),
            ],
            options={
                'ordering': ['-year', '-month_sequence'],
            },
        ),
        migrations.CreateModel(
            name='AttendancerequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='AttendancerequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance/request_files')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceValidationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_at_work', models.CharField(max_length=10, validators=[attendance.models.validate_time_format])),
                ('minimum_overtime_to_approve', models.CharField(blank=True, max_length=10, null=True, validators=[attendance.models.validate_time_format])),
                ('overtime_cutoff', models.CharField(blank=True, max_length=10, null=True, validators=[attendance.models.validate_time_format])),
            ],
        ),
        migrations.CreateModel(
            name='GraceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_time', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_in_minutes], verbose_name='Allowed time')),
                ('allowed_time_in_secs', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAttendance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_title', models.CharField(blank=True, max_length=20, null=True)),
                ('history_description', models.TextField(null=True)),
                ('history_highlight', models.BooleanField(default=False, null=True)),
                ('attendance_date', models.DateField(validators=[attendance.models.attendance_date_validate], verbose_name='Attendance date')),
                ('attendance_clock_in_date', models.DateField(null=True, verbose_name='Check-In Date')),
                ('attendance_clock_in', models.TimeField(help_text='First Check-In Time', null=True, verbose_name='Check-In')),
                ('attendance_clock_out_date', models.DateField(null=True, verbose_name='Check-Out Date')),
                ('attendance_clock_out', models.TimeField(help_text='Last Check-Out Time', null=True, verbose_name='Check-Out')),
                ('attendance_worked_hour', models.CharField(default='00:00', max_length=10, null=True, validators=[attendance.models.validate_time_format], verbose_name='Worked Hours')),
                ('minimum_hour', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format], verbose_name='Minimum hour')),
                ('attendance_overtime', models.CharField(default='00:00', max_length=10, validators=[attendance.models.validate_time_format], verbose_name='Overtime')),
                ('attendance_overtime_approve', models.BooleanField(default=False, verbose_name='Overtime approved')),
                ('attendance_validated', models.BooleanField(default=False, verbose_name='Attendance validated')),
                ('at_work_second', models.IntegerField(blank=True, null=True)),
                ('overtime_second', models.IntegerField(blank=True, null=True, verbose_name='Overtime In Second')),
                ('approved_overtime_second', models.IntegerField(default=0)),
                ('is_validate_request', models.BooleanField(default=False, verbose_name='Is validate request')),
                ('is_validate_request_approved', models.BooleanField(default=False, verbose_name='Is validate request approved')),
                ('request_description', models.TextField(null=True)),
                ('request_type', models.CharField(choices=[('create_request', 'Create Request'), ('update_request', 'Update Request'), ('revalidate_request', 'Re-validate Request')], default='update_request', max_length=18, null=True)),
                ('requested_data', models.JSONField(editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical attendance',
                'verbose_name_plural': 'historical attendances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PenaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_leaves', models.FloatField(default=0.0, null=True)),
                ('deduct_from_carry_forward', models.BooleanField(default=False)),
                ('penalty_amount', models.FloatField(default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
