# Generated by Django 4.2.7 on 2024-02-17 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('base', '0001_initial'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
        ('horilla_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyaccount',
            name='employee_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_set', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='penaltyaccount',
            name='late_early_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancelatecomeearlyout'),
        ),
        migrations.AddField(
            model_name='penaltyaccount',
            name='leave_request_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leaverequest'),
        ),
        migrations.AddField(
            model_name='penaltyaccount',
            name='leave_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attendance_day',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.employeeshiftday', verbose_name='Attendance day'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_set', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='history_tags',
            field=models.ManyToManyField(to='horilla_audit.audittag'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='shift_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='work_type_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.worktype', verbose_name='Work Type'),
        ),
        migrations.AddField(
            model_name='gracetime',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='attendancevalidationcondition',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='attendancerequestcomment',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendancerequestcomment',
            name='files',
            field=models.ManyToManyField(blank=True, to='attendance.attendancerequestfile'),
        ),
        migrations.AddField(
            model_name='attendancerequestcomment',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceovertime',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_overtime', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendancelatecomeearlyout',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_come_early_out', to='attendance.attendance', verbose_name='Attendance'),
        ),
        migrations.AddField(
            model_name='attendancelatecomeearlyout',
            name='employee_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='late_come_early_out', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendancegeneralsetting',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendance_activities', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='shift_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshiftday', verbose_name='Shift Day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshiftday', verbose_name='Attendance day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendances', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshift', verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.worktype', verbose_name='Work Type'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceovertime',
            unique_together={('employee_id', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancelatecomeearlyout',
            unique_together={('attendance_id', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_id', 'attendance_date')},
        ),
    ]
