# Generated by Django 4.1.4 on 2023-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('base', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceovertime',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overtime', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendancelatecomeearlyout',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_come_early_out', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendancelatecomeearlyout',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='late_come_early_out', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_activities', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='shift_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshiftday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshiftday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.worktype'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceovertime',
            unique_together={('employee_id', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancelatecomeearlyout',
            unique_together={('attendance_id', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_id', 'attendance_date')},
        ),
    ]
