# Generated by Django 6.0 on 2026-01-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceovertime',
            name='year',
            field=models.CharField(default='2026', max_length=10, null=True, verbose_name='Year'),
        ),
    ]
