# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_historicalattendanceactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceovertime',
            options={'ordering': ['-year', '-month_sequence'], 'verbose_name': 'Hours Balance', 'verbose_name_plural': 'Hours Balances'},
        ),
        migrations.AlterModelOptions(
            name='workrecords',
            options={'verbose_name': 'Daily Work Status', 'verbose_name_plural': 'Daily Work Status'},
        ),
        migrations.AlterField(
            model_name='attendancelatecomeearlyout',
            name='type',
            field=models.CharField(choices=[('late_come', 'Late Arrival'), ('early_out', 'Early Departure')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='workrecords',
            name='work_record_type',
            field=models.CharField(choices=[('FDP', 'Present'), ('HDP', 'Half Day Present'), ('ABS', 'Absent'), ('HD', 'Holiday / Weekly Off'), ('CONF', 'Conflict'), ('DFT', 'Draft')], max_length=10, null=True),
        ),
    ]
