# Generated by Django 5.2 on 2026-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendanceovertime_options_and_more'),
        ('base', '0011_alter_companyleaves_options_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
        ('leave', '0007_alter_historicalleaverequest_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workrecords',
            constraint=models.UniqueConstraint(fields=('employee_id', 'date'), name='unique_work_record_per_employee_per_date'),
        ),
    ]
