# Generated by Django 5.2 on 2026-08-10 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_workrecords_unique_work_record_per_employee_per_date'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date', models.DateField(verbose_name='Date')),
                ('resolution', models.CharField(choices=[('full_present', 'Full Present'), ('half_present', 'Half Day'), ('partial_hours', 'Partial Hours'), ('absent', 'Absent'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off'), ('attendance', 'Count as Attendance'), ('leave', 'Count as Leave / Holiday')], max_length=20, verbose_name='Resolution')),
                ('conflict_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Conflict Type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_resolutions', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Conflict Resolution',
                'verbose_name_plural': 'Attendance Conflict Resolutions',
                'unique_together': {('employee_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceDailyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours_second', models.IntegerField(default=0, verbose_name='Hours (seconds)')),
                ('is_manually_edited', models.BooleanField(default=False, verbose_name='Manually Edited')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_hours', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Daily Hours',
                'verbose_name_plural': 'Attendance Daily Hours',
                'unique_together': {('employee_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummaryHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('hours_second', models.IntegerField(default=0, verbose_name='Hours (seconds)')),
                ('is_manually_edited', models.BooleanField(default=False, verbose_name='Manually Edited')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_hours', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Summary Hours',
                'verbose_name_plural': 'Attendance Summary Hours',
                'unique_together': {('employee_id', 'from_date', 'to_date')},
            },
        ),
    ]
