# Generated by Django 5.2.17 on 2026-09-02 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceconflictresolution_attendancedailyhours_and_more'),
        ('base', '0014_alter_rotatingworktype_name'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'attendance_validated'], name='attendance_date_validated_idx'),
        ),
    ]
