# Generated by Django 4.2.24 on 2026-07-14 18:20

from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('company_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_detection', to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=horilla.models.upload_path)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_detection', to='employee.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='facedetection',
            constraint=models.UniqueConstraint(condition=models.Q(('company_id', None), _negated=True), fields=('company_id',), name='unique_company_id_when_not_null_facedetection'),
        ),
    ]
