# Generated by Django 5.2 on 2026-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetection',
            name='start',
            field=models.BooleanField(default=False, verbose_name='Start'),
        ),
    ]
