name: Build and Push Horilla Docker Image

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (for advanced Docker builds, including multi-platform)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image to GitHub Container Registry
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Build the Dockerfile in the repository's root
        file: ./Dockerfile  # Specify the Dockerfile location
        push: true  # Push the image after building
        tags: |
          ghcr.io/${{ github.repository_owner }}/horilla:latest  # Tag with latest
          ghcr.io/${{ github.repository_owner }}/horilla:${{ github.sha }}  # Tag with the commit SHA

    # Log out from Docker (optional)
    - name: Log out from Docker
      run: docker logout ghcr.io
