# Generated by Django 4.2.24 on 2026-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_credentials_file', models.FileField(blank=True, help_text='Make sure your file is in JSON format and contains your Google OAuth 2.0 client credentials (web application type)', null=True, upload_to='gdrive_oauth_credentials_file', verbose_name='OAuth Credentials File')),
                ('gdrive_folder_id', models.CharField(help_text='Google Drive folder ID where backups will be stored. The authenticated user must have write access to this folder.', max_length=255, verbose_name='Gdrive Folder ID')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (automatically managed)', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (automatically managed)', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Token expiry time (automatically managed)', null=True)),
                ('backup_media', models.BooleanField(blank=True, null=True)),
                ('backup_db', models.BooleanField(blank=True, null=True)),
                ('interval', models.BooleanField(blank=True, null=True)),
                ('fixed', models.BooleanField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(help_text='Specify the path in the server were the backup files should keep', max_length=255)),
                ('backup_media', models.BooleanField(blank=True, null=True)),
                ('backup_db', models.BooleanField(blank=True, null=True)),
                ('interval', models.BooleanField(blank=True, null=True)),
                ('fixed', models.BooleanField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
