# Generated by Django 5.2.7 on 2025-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleDriveBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_account_file",
                    models.FileField(
                        help_text="Make sure your file is in JSON format and contains your Google Service Account credentials",
                        upload_to="gdrive_service_account_file",
                        verbose_name="Service Account File",
                    ),
                ),
                (
                    "gdrive_folder_id",
                    models.CharField(
                        help_text="Shared Gdrive folder Id with access granted to Gmail service account. Enable full permissions for seamless connection.",
                        max_length=255,
                        verbose_name="Gdrive Folder ID",
                    ),
                ),
                ("backup_media", models.BooleanField(blank=True, null=True)),
                ("backup_db", models.BooleanField(blank=True, null=True)),
                ("interval", models.BooleanField(blank=True, null=True)),
                ("fixed", models.BooleanField(blank=True, null=True)),
                ("seconds", models.IntegerField(blank=True, null=True)),
                ("hour", models.IntegerField(blank=True, null=True)),
                ("minute", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LocalBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        help_text="Specify the path in the server were the backup files should keep",
                        max_length=255,
                    ),
                ),
                ("backup_media", models.BooleanField(blank=True, null=True)),
                ("backup_db", models.BooleanField(blank=True, null=True)),
                ("interval", models.BooleanField(blank=True, null=True)),
                ("fixed", models.BooleanField(blank=True, null=True)),
                ("seconds", models.IntegerField(blank=True, null=True)),
                ("hour", models.IntegerField(blank=True, null=True)),
                ("minute", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
