# Generated by Django 5.2 on 2026-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivebackup',
            name='service_account_file',
        ),
        migrations.AddField(
            model_name='googledrivebackup',
            name='access_token',
            field=models.TextField(blank=True, help_text='OAuth access token (automatically managed)', null=True),
        ),
        migrations.AddField(
            model_name='googledrivebackup',
            name='oauth_credentials_file',
            field=models.FileField(blank=True, help_text='Make sure your file is in JSON format and contains your Google OAuth 2.0 client credentials (web application type)', null=True, upload_to='gdrive_oauth_credentials_file', verbose_name='OAuth Credentials File'),
        ),
        migrations.AddField(
            model_name='googledrivebackup',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token (automatically managed)', null=True),
        ),
        migrations.AddField(
            model_name='googledrivebackup',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='Token expiry time (automatically managed)', null=True),
        ),
        migrations.AlterField(
            model_name='googledrivebackup',
            name='gdrive_folder_id',
            field=models.CharField(help_text='Google Drive folder ID where backups will be stored. The authenticated user must have write access to this folder.', max_length=255, verbose_name='Gdrive Folder ID'),
        ),
    ]
