# Generated by Django 5.2 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_backup', '0002_remove_googledrivebackup_service_account_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivebackup',
            name='gdrive_folder_id',
            field=models.CharField(help_text='Google Drive folder ID where backups will be stored. The authenticated user must have write access to this folder.', max_length=255, verbose_name='Google Drive Folder ID'),
        ),
    ]
